<?php
/**
 * @package     RedSHOP.Backend
 * @subpackage  Template
 *
 * @copyright   Copyright (C) 2005 - 2013 redCOMPONENT.com. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE
 */
defined('_JEXEC') or die ('Restricted access');

?>
<table class="admintable">
	<tr>
		<td width="100" align="right" class="key">
		<span class="editlinktip hasTip"
		      title="<?php echo JText::_('COM_REDSHOP_CLEAR_SEF_URLS_LBL'); ?>::<?php echo JText::_('COM_REDSHOP_TOOLTIP_CLEAR_SEF_URLS'); ?>">
		<label for="seo_page_robots">
			<?php
			echo JText::_('COM_REDSHOP_CLEAR_SEF_URLS_LBL');
			?>
		</label></span></td>
		<td>
			<div>
				<div style="float: left;">
					<button onclick="clearsef();return false;" name="cleansef"
					        id="cleansef"><?php
						echo JText::_('COM_REDSHOP_CLEAN_SEF_URLS');
						?></button>
				</div>
				<div id="responce_clear" align="right"></div>
			</div>
		</td>
	</tr>
	<tr>
		<td width="100" align="right" class="key">
		<span class="editlinktip hasTip"
		      title="<?php echo JText::_('COM_REDSHOP_ENABLE_SEF_PRODUCT_NUMBER_LBL'); ?>::<?php echo JText::_('COM_REDSHOP_TOOLTIP_ENABLE_SEF_PRODUCT_NUMBER_LBL'); ?>">
		<label
			for="enable_sef_product_number"><?php
			echo JText::_('COM_REDSHOP_ENABLE_SEF_PRODUCT_NUMBER_LBL');
			?></label></span>
		</td>
		<td>
			<?php
			echo $this->lists ['enable_sef_product_number'];
			?>
		</td>
	</tr>
	<tr>
		<td width="100" align="right" class="key">
		<span class="editlinktip hasTip"
		      title="<?php echo JText::_('COM_REDSHOP_TOOLTIP_ENABLE_SEF_NUMBER_NAME_LBL'); ?>::<?php echo JText::_('COM_REDSHOP_TOOLTIP_ENABLE_SEF_NUMBER_NAME_LBL'); ?>">
		<label
			for="enable_sef_product_number"><?php
			echo JText::_('COM_REDSHOP_ENABLE_SEF_NUMBER_NAME_LBL');
			?></label>
		</td>
		<td>
			<?php
			echo $this->lists ['enable_sef_number_name'];
			?>
		</td>
	</tr>
	<tr>
		<td width="100" align="right" class="key">
		<span class="editlinktip hasTip"
		      title="<?php echo JText::_('COM_REDSHOP_TOOLTIP_CATEGORY_IN_SEF_URL_LBL'); ?>::<?php echo JText::_('COM_REDSHOP_TOOLTIP_CATEGORY_IN_SEF_URL_LBL'); ?>">
		<label
			for="enable_sef_product_number"><?php
			echo JText::_('COM_REDSHOP_CATEGORY_IN_SEF_URL');
			?></label>
		</td>
		<td>
			<?php
			echo $this->lists ['category_in_sef_url'];
			?>
		</td>
	</tr>
	<tr>
		<td width="100" align="right" class="key">
		<span class="editlinktip hasTip"
		      title="<?php echo JText::_('COM_REDSHOP_TOOLTIP_CATEGORY_TREE_IN_SEF_URL_HEAD'); ?>::<?php echo JText::_('COM_REDSHOP_TOOLTIP_CATEGORY_TREE_IN_SEF_URL_LBL'); ?>">
		<label
			for="enable_sef_product_number"><?php
			echo JText::_('COM_REDSHOP_CATEGORY_TREE_IN_SEF_URL');
			?></label>
		</td>
		<td>
			<?php
			if (!defined('CATEGORY_TREE_IN_SEF_URL'))
			{
				define('CATEGORY_TREE_IN_SEF_URL', 0);
			}

			echo JHTML::_('select.booleanlist', 'category_tree_in_sef_url', 'class="inputbox"', CATEGORY_TREE_IN_SEF_URL);
			?>
		</td>
	</tr>
	<tr>
		<td width="100" align="right" class="key">
		<span class="editlinktip hasTip"
		      title="<?php echo JText::_('COM_REDSHOP_AUTOGENERATED_SEO_LBL'); ?>::<?php echo JText::_('COM_REDSHOP_TOOLTIP_AUTOGENERATED_SEO_LBL'); ?>">
		<label
			for="autogenerated_seo">
			<?php
			echo JText::_('COM_REDSHOP_AUTOGENERATED_SEO_LBL');
			?>
		</label></span></td>
		<td>
			<?php
			echo $this->lists ['autogenerated_seo'];
			?>
		</td>
	</tr>
	<tr>
		<td width="100" align="right" class="key">
		<span class="editlinktip hasTip"
		      title="<?php echo JText::_('COM_REDSHOP_SEO_PAGE_LANGAUGE_LBL'); ?>::<?php echo JText::_('COM_REDSHOP_TOOLTIP_SEO_PAGE_LANGAUGE'); ?>">
		<label
			for="seo_page_language">
			<?php
			echo JText::_('COM_REDSHOP_SEO_PAGE_LANGAUGE_LBL');
			?>
		</label></span></td>
		<td><textarea class="text_area" type="text" name="seo_page_language"
		              id="seo_page_language" rows="4" cols="40"/><?php
			echo stripslashes(SEO_PAGE_LANGAUGE);
			?></textarea>
		</td>
	</tr>
	<tr>
		<td width="100" align="right" class="key">
		<span class="editlinktip hasTip"
		      title="<?php echo JText::_('COM_REDSHOP_SEO_PAGE_ROBOTS_LBL'); ?>::<?php echo JText::_('COM_REDSHOP_TOOLTIP_SEO_PAGE_ROBOTS'); ?>">
		<label for="seo_page_robots">
			<?php
			echo JText::_('COM_REDSHOP_SEO_PAGE_ROBOTS_LBL');
			?>
		</label></span></td>
		<td><textarea class="text_area" type="text" name="seo_page_robots"
		              id="seo_page_robots" rows="4" cols="40"/><?php
			echo stripslashes(SEO_PAGE_ROBOTS);
			?></textarea>
		</td>
	</tr>
</table>
