<div>{attribute_title}</div>
<div>
<table border="0">
<tbody>
<tr>
<td>{image_lbl}</td>
<td>{virtual_number_lbl}</td>
<td>{name_lbl}</td>
<td>{price_lbl}</td>
<td>{stock_lbl}</td>
<td>{add_to_cart_lbl}</td>
</tr>
{property_start}    
<tr>
<td>{property_image}</td>
<td>{virtual_number}</td>
<td>{property_name}</td>
<td>{property_oprand}{property_price}</td>
<td>{property_stock}</td>
<td>{form_addtocart:add_to_cart1}</td>
</tr>
{property_end}
</tbody>
</table>
</div>