pipeline:
  clone:
    image: plugins/git
    depth: 1
    recursive: true

  system-tests-setup:
    image: jatitoam/docker-systemtests
    environment:
      - CLOUD_NAME=redcomponent
      - API_KEY=365447364384436
      - API_SECRET=Q94UM5kjZkZIrau8MIL93m0dN6U
      - GITHUB_TOKEN=72e1853aca389b4834d880cfe0b86e2af15d7fb9
      - ORGANIZATION=redCOMPONENT-COM
      - SLACK_WEBHOOK='https://hooks.slack.com/services/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'
      - SLACK_CHANNEL='#redshop-builds'
      - GITHUB_REPO_OWNER='redCOMPONENT-COM'
      - REPO='redSHOP'
      - GITHUB_REPO='redCOMPONENT-COM/redSHOP'
      - STEP_NAME=setup
    volumes:
      - /root/drone/redshop-vendor:/vendor
    commands:
      - ls -la
      - whoami
      - pwd
      - ls -la
      - ./build/test-setup.sh

  system-tests-admin:
      image: jatitoam/docker-systemtests
      group: build
      environment:
        - CLOUD_NAME=redcomponent
        - API_KEY=365447364384436
        - API_SECRET=Q94UM5kjZkZIrau8MIL93m0dN6U
        - GITHUB_TOKEN=72e1853aca389b4834d880cfe0b86e2af15d7fb9
        - ORGANIZATION=redCOMPONENT-COM
        - SLACK_WEBHOOK='https://hooks.slack.com/services/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'
        - SLACK_CHANNEL='#redshop-builds'
        - GITHUB_REPO_OWNER='redCOMPONENT-COM'
        - REPO='redSHOP'
        - GITHUB_REPO='redCOMPONENT-COM/redSHOP'
        - STEP_NAME=admin
      volumes:
        - /root/drone/redshop-vendor:/vendor
      commands:
        - ls -la
        - whoami
        - pwd
        - ls -la
        - ./build/system-tests.sh administrator

  system-tests-integration:
      image: jatitoam/docker-systemtests
      group: build
      environment:
        - CLOUD_NAME=redcomponent
        - API_KEY=365447364384436
        - API_SECRET=Q94UM5kjZkZIrau8MIL93m0dN6U
        - GITHUB_TOKEN=72e1853aca389b4834d880cfe0b86e2af15d7fb9
        - ORGANIZATION=redCOMPONENT-COM
        - SLACK_WEBHOOK='https://hooks.slack.com/services/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'
        - SLACK_CHANNEL='#redshop-builds'
        - GITHUB_REPO_OWNER='redCOMPONENT-COM'
        - REPO='redSHOP'
        - GITHUB_REPO='redCOMPONENT-COM/redSHOP'
        - STEP_NAME=integration
      volumes:
        - /root/drone/redshop-vendor:/vendor
      commands:
        - ls -la
        - whoami
        - pwd
        - ls -la
        - ./build/system-tests.sh integration
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: joomla_ut
      MYSQL_PASSWORD: joomla_ut
      MYSQL_ROOT_PASSWORD: joomla_ut
      MYSQL_DATABASE: test_joomla