preserve_hierarchy: true
files:
  - source: >-
      /component/admin/language/en-GB/en-GB.com_redshop.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.com_redshop.ini
  - source: >-
      /component/admin/language/en-GB/en-GB.com_redshop.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.com_redshop.sys.ini
  - source: >-
      /component/site/language/en-GB/en-GB.com_redshop.ini
    translation: >-
      /src/lang/%locale%/site/%locale%/%locale%.com_redshop.ini
  - source: >-
      /libraries/redshop/language/en-GB/en-GB.lib_redshop.ini
    translation: >-
      /src/lang/%locale%/site/%locale%/%locale%.lib_redshop.ini
  - source: >-
      /libraries/redshop/language/en-GB/en-GB.lib_redshop.sys.ini
    translation: >-
      /src/lang/%locale%/site/%locale%/%locale%.lib_redshop.sys.ini
  - source: >-
      /modules/site/mod_redshop_cart/language/en-GB/en-GB.mod_redshop_cart.ini
    translation: >-
      /src/lang/%locale%/site/%locale%/%locale%.mod_redshop_cart.ini
  - source: >-
      /modules/site/mod_redshop_cart/language/en-GB/en-GB.mod_redshop_cart.sys.ini
    translation: >-
      /src/lang/%locale%/site/%locale%/%locale%.mod_redshop_cart.sys.ini
  - source: >-
      /modules/site/mod_redshop_search/language/en-GB/en-GB.mod_redshop_search.ini
    translation: >-
      /src/lang/%locale%/site/%locale%/%locale%.mod_redshop_search.ini
  - source: >-
      /modules/site/mod_redshop_search/language/en-GB/en-GB.mod_redshop_search.sys.ini
    translation: >-
      /src/lang/%locale%/site/%locale%/%locale%.mod_redshop_search.sys.ini
  - source: >-
      /plugins/finder/redshop/language/en-GB/en-GB.plg_finder_redshop.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_finder_redshop.ini
  - source: >-
      /plugins/finder/redshop/language/en-GB/en-GB.plg_finder_redshop.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_finder_redshop.sys.ini
  - source: >-
      /plugins/quickicon/redshop/language/en-GB/en-GB.plg_quickicon_redshop.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_quickicon_redshop.ini
  - source: >-
      /plugins/quickicon/redshop/language/en-GB/en-GB.plg_quickicon_redshop.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_quickicon_redshop.sys.ini
  - source: >-
      /plugins/redshop_alert/alert/language/en-GB/en-GB.plg_redshop_alert_alert.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_alert_alert.ini
  - source: >-
      /plugins/redshop_alert/alert/language/en-GB/en-GB.plg_redshop_alert_alert.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_alert_alert.sys.ini
  - source: >-
      /plugins/redshop_export/attribute/language/en-GB/en-GB.plg_redshop_export_attribute.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_export_attribute.ini
  - source: >-
      /plugins/redshop_export/attribute/language/en-GB/en-GB.plg_redshop_export_attribute.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_export_attribute.sys.ini
  - source: >-
      /plugins/redshop_export/category/language/en-GB/en-GB.plg_redshop_export_category.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_export_category.ini
  - source: >-
      /plugins/redshop_export/category/language/en-GB/en-GB.plg_redshop_export_category.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_export_category.sys.ini
  - source: >-
      /plugins/redshop_export/field/language/en-GB/en-GB.plg_redshop_export_field.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_export_field.ini
  - source: >-
      /plugins/redshop_export/field/language/en-GB/en-GB.plg_redshop_export_field.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_export_field.sys.ini
  - source: >-
      /plugins/redshop_export/manufacturer/language/en-GB/en-GB.plg_redshop_export_manufacturer.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_export_manufacturer.ini
  - source: >-
      /plugins/redshop_export/manufacturer/language/en-GB/en-GB.plg_redshop_export_manufacturer.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_export_manufacturer.sys.ini
  - source: >-
      /plugins/redshop_export/newsletter_subscriber/language/en-GB/en-GB.plg_redshop_export_newsletter_subscriber.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_export_newsletter_subscriber.ini
  - source: >-
      /plugins/redshop_export/newsletter_subscriber/language/en-GB/en-GB.plg_redshop_export_newsletter_subscriber.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_export_newsletter_subscriber.sys.ini
  - source: >-
      /plugins/redshop_export/product/language/en-GB/en-GB.plg_redshop_export_product.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_export_product.ini
  - source: >-
      /plugins/redshop_export/product/language/en-GB/en-GB.plg_redshop_export_product.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_export_product.sys.ini
  - source: >-
      /plugins/redshop_export/product_stockroom_data/language/en-GB/en-GB.plg_redshop_export_product_stockroom_data.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_export_product_stockroom_data.ini
  - source: >-
      /plugins/redshop_export/product_stockroom_data/language/en-GB/en-GB.plg_redshop_export_product_stockroom_data.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_export_product_stockroom_data.sys.ini
  - source: >-
      /plugins/redshop_export/related_product/language/en-GB/en-GB.plg_redshop_export_related_product.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_export_related_product.ini
  - source: >-
      /plugins/redshop_export/related_product/language/en-GB/en-GB.plg_redshop_export_related_product.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_export_related_product.sys.ini
  - source: >-
      /plugins/redshop_export/shipping_address/language/en-GB/en-GB.plg_redshop_export_shipping_address.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_export_shipping_address.ini
  - source: >-
      /plugins/redshop_export/shipping_address/language/en-GB/en-GB.plg_redshop_export_shipping_address.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_export_shipping_address.sys.ini
  - source: >-
      /plugins/redshop_export/shopper_group_attribute_price/language/en-GB/en-GB.plg_redshop_export_shopper_group_attribute_price.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_export_shopper_group_attribute_price.ini
  - source: >-
      /plugins/redshop_export/shopper_group_attribute_price/language/en-GB/en-GB.plg_redshop_export_shopper_group_attribute_price.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_export_shopper_group_attribute_price.sys.ini
  - source: >-
      /plugins/redshop_export/shopper_group_product_price/language/en-GB/en-GB.plg_redshop_export_shopper_group_product_price.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_export_shopper_group_product_price.ini
  - source: >-
      /plugins/redshop_export/shopper_group_product_price/language/en-GB/en-GB.plg_redshop_export_shopper_group_product_price.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_export_shopper_group_product_price.sys.ini
  - source: >-
      /plugins/redshop_export/user/language/en-GB/en-GB.plg_redshop_export_user.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_export_user.ini
  - source: >-
      /plugins/redshop_export/user/language/en-GB/en-GB.plg_redshop_export_user.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_export_user.sys.ini
  - source: >-
      /plugins/redshop_import/attribute/language/en-GB/en-GB.plg_redshop_import_attribute.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_import_attribute.ini
  - source: >-
      /plugins/redshop_import/attribute/language/en-GB/en-GB.plg_redshop_import_attribute.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_import_attribute.sys.ini
  - source: >-
      /plugins/redshop_import/category/language/en-GB/en-GB.plg_redshop_import_category.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_import_category.ini
  - source: >-
      /plugins/redshop_import/category/language/en-GB/en-GB.plg_redshop_import_category.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_import_category.sys.ini
  - source: >-
      /plugins/redshop_import/field/language/en-GB/en-GB.plg_redshop_import_field.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_import_field.ini
  - source: >-
      /plugins/redshop_import/field/language/en-GB/en-GB.plg_redshop_import_field.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_import_field.sys.ini
  - source: >-
      /plugins/redshop_import/manufacturer/language/en-GB/en-GB.plg_redshop_import_manufacturer.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_import_manufacturer.ini
  - source: >-
      /plugins/redshop_import/manufacturer/language/en-GB/en-GB.plg_redshop_import_manufacturer.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_import_manufacturer.sys.ini
  - source: >-
      /plugins/redshop_import/newsletter_subscriber/language/en-GB/en-GB.plg_redshop_import_newsletter_subscriber.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_import_newsletter_subscriber.ini
  - source: >-
      /plugins/redshop_import/newsletter_subscriber/language/en-GB/en-GB.plg_redshop_import_newsletter_subscriber.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_import_newsletter_subscriber.sys.ini
  - source: >-
      /plugins/redshop_import/product/language/en-GB/en-GB.plg_redshop_import_product.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_import_product.ini
  - source: >-
      /plugins/redshop_import/product/language/en-GB/en-GB.plg_redshop_import_product.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_import_product.sys.ini
  - source: >-
      /plugins/redshop_import/product_stockroom_data/language/en-GB/en-GB.plg_redshop_import_product_stockroom_data.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_import_product_stockroom_data.ini
  - source: >-
      /plugins/redshop_import/product_stockroom_data/language/en-GB/en-GB.plg_redshop_import_product_stockroom_data.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_import_product_stockroom_data.sys.ini
  - source: >-
      /plugins/redshop_import/related_product/language/en-GB/en-GB.plg_redshop_import_related_product.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_import_related_product.ini
  - source: >-
      /plugins/redshop_import/related_product/language/en-GB/en-GB.plg_redshop_import_related_product.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_import_related_product.sys.ini
  - source: >-
      /plugins/redshop_import/shipping_address/language/en-GB/en-GB.plg_redshop_import_shipping_address.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_import_shipping_address.ini
  - source: >-
      /plugins/redshop_import/shipping_address/language/en-GB/en-GB.plg_redshop_import_shipping_address.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_import_shipping_address.sys.ini
  - source: >-
      /plugins/redshop_import/shopper_group_attribute_price/language/en-GB/en-GB.plg_redshop_import_shopper_group_attribute_price.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_import_shopper_group_attribute_price.ini
  - source: >-
      /plugins/redshop_import/shopper_group_attribute_price/language/en-GB/en-GB.plg_redshop_import_shopper_group_attribute_price.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_import_shopper_group_attribute_price.sys.ini
  - source: >-
      /plugins/redshop_import/shopper_group_product_price/language/en-GB/en-GB.plg_redshop_import_shopper_group_product_price.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_import_shopper_group_product_price.ini
  - source: >-
      /plugins/redshop_import/shopper_group_product_price/language/en-GB/en-GB.plg_redshop_import_shopper_group_product_price.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_import_shopper_group_product_price.sys.ini
  - source: >-
      /plugins/redshop_import/user/language/en-GB/en-GB.plg_redshop_import_user.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_import_user.ini
  - source: >-
      /plugins/redshop_import/user/language/en-GB/en-GB.plg_redshop_import_user.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_import_user.sys.ini
  - source: >-
      /plugins/redshop_payment/rs_payment_banktransfer/language/en-GB/en-GB.plg_redshop_payment_rs_payment_banktransfer.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_payment_rs_payment_banktransfer.ini
  - source: >-
      /plugins/redshop_payment/rs_payment_banktransfer/language/en-GB/en-GB.plg_redshop_payment_rs_payment_banktransfer.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_payment_rs_payment_banktransfer.sys.ini
  - source: >-
      /plugins/redshop_payment/rs_payment_paypal/language/en-GB/en-GB.plg_redshop_payment_rs_payment_paypal.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_payment_rs_payment_paypal.ini
  - source: >-
      /plugins/redshop_payment/rs_payment_paypal/language/en-GB/en-GB.plg_redshop_payment_rs_payment_paypal.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_payment_rs_payment_paypal.sys.ini
  - source: >-
      /plugins/redshop_pdf/tcpdf/language/en-GB/en-GB.plg_redshop_pdf_tcpdf.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_pdf_tcpdf.ini
  - source: >-
      /plugins/redshop_pdf/tcpdf/language/en-GB/en-GB.plg_redshop_pdf_tcpdf.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_pdf_tcpdf.sys.ini
  - source: >-
      /plugins/redshop_shipping/default_shipping/language/en-GB/en-GB.plg_redshop_shipping_default_shipping.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_shipping_default_shipping.ini
  - source: >-
      /plugins/redshop_shipping/default_shipping/language/en-GB/en-GB.plg_redshop_shipping_default_shipping.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_redshop_shipping_default_shipping.sys.ini
  - source: >-
      /plugins/search/redshop_categories/language/en-GB/en-GB.plg_search_redshop_categories.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_search_redshop_categories.ini
  - source: >-
      /plugins/search/redshop_categories/language/en-GB/en-GB.plg_search_redshop_categories.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_search_redshop_categories.sys.ini
  - source: >-
      /plugins/search/redshop_products/language/en-GB/en-GB.plg_search_redshop_products.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_search_redshop_products.ini
  - source: >-
      /plugins/search/redshop_products/language/en-GB/en-GB.plg_search_redshop_products.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_search_redshop_products.sys.ini
  - source: >-
      /plugins/sh404sefextplugins/sh404sefextplugincom_redshop/language/en-GB/en-GB.plg_sh404sefextplugins_sh404sefextplugincom_redshop.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_sh404sefextplugins_sh404sefextplugincom_redshop.ini
  - source: >-
      /plugins/sh404sefextplugins/sh404sefextplugincom_redshop/language/en-GB/en-GB.plg_sh404sefextplugins_sh404sefextplugincom_redshop.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_sh404sefextplugins_sh404sefextplugincom_redshop.sys.ini
  - source: >-
      /plugins/system/redgoogleanalytics/language/en-GB/en-GB.plg_system_redgoogleanalytics.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_system_redgoogleanalytics.ini
  - source: >-
      /plugins/system/redgoogleanalytics/language/en-GB/en-GB.plg_system_redgoogleanalytics.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_system_redgoogleanalytics.sys.ini
  - source: >-
      /plugins/system/redshop/language/en-GB/en-GB.plg_system_redshop.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_system_redshop.ini
  - source: >-
      /plugins/system/redshop/language/en-GB/en-GB.plg_system_redshop.sys.ini
    translation: >-
      /src/lang/%locale%/admin/%locale%/%locale%.plg_system_redshop.sys.ini