version: "3.6"
services:
  joomla:
    image: joomla:3.8-php7.0
    restart: always
    links:
      - joomladb:mysql
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: ./tests/joomla-cms3
        target: /var/www/html
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: root
  joomladb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

networks:
  webnet:

volumes:
  mydata: