<?php define ('FEDEX_ACCOUNT_NUMBER', '');
define ('FEDEX_METER_NUMBER', '');
define ('FEDEX_CARRIERCODE', 'FDXG');
define ('FEDEX_SERVICETYPE', 'a:8:{i:0;s:18:"PRIORITY_OVERNIGHT";i:1;s:18:"STANDARD_OVERNIGHT";i:2;s:15:"FIRST_OVERNIGHT";i:3;s:11:"FEDEX_2_DAY";i:4;s:12:"FEDEX_GROUND";i:5;s:30:"INTERNATIONAL_PRIORITY_FREIGHT";i:6;s:29:"INTERNATIONAL_ECONOMY_FREIGHT";i:7;s:35:"EUROPE_FIRST_INTERNATIONAL_PRIORITY";}');
define ('FEDEX_DROPOFFTYPE', 'REGULAR_PICKUP');
define ('FEDEX_PACKAGINGTYPE', 'FEDEX_ENVELOPE');
define ('FEDEX_WEIGHTUNITS', 'lbs');
define ('FEDEX_DEVELOPMENT', '1');
define ('FEDEX_KEY', '');
define ('FEDEX_PASSWORD', '');
define ('FEDEX_SHIPPER_ADDRESS', '');
define ('FEDEX_SHIPPER_CITY', '');
define ('FEDEX_SHIPPER_STATE', '');
define ('FEDEX_SHIPPER_POSTAL_CODE', '');
define ('FEDEX_SHIPPER_COUNTRY_CODE', '');
define ('FEDEX_DISCOUNT', '0');
?>