ALTER TABLE `#__redshop_media` CHANGE `media_id` `id` INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `#__redshop_media` CHANGE `media_name` `name` VARCHAR(250) NOT NULL;
ALTER TABLE `#__redshop_media` CHANGE `media_alternate_text` `alternate_text` VARCHAR(255) NOT NULL;
ALTER TABLE `#__redshop_media` CHANGE `media_section` `section` VARCHAR(20) NOT NULL;
ALTER TABLE `#__redshop_media` CHANGE `media_type` `type` VARCHAR(255) NOT NULL;
ALTER TABLE `#__redshop_media` CHANGE `media_mimetype` `mimetype` VARCHAR(20) NOT NULL;
ALTER TABLE `#__redshop_media` ADD `youtube_id` INT(11) NULL AFTER `section_id`;
ALTER TABLE `#__redshop_media` ADD `title` VARCHAR(255) NULL AFTER `id`;
ALTER TABLE `#__redshop_media` ADD `checked_out` INT(11) NULL AFTER `mimetype`;
ALTER TABLE `#__redshop_media` ADD `checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00'  AFTER `mimetype`;
ALTER TABLE `#__redshop_media` ADD `created_by` INT(11) NULL AFTER `checked_out_time`;
ALTER TABLE `#__redshop_media` ADD `created_date` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' AFTER `created_by`;
ALTER TABLE `#__redshop_media` ADD `modified_by` INT(11) NULL AFTER `created_date`;
ALTER TABLE `#__redshop_media` ADD `modified_date` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' AFTER `modified_by`;