ALTER TABLE `#__redshop_category` CHANGE `short_description` `short_description` LONGTEXT NULL;
ALTER TABLE `#__redshop_category` CHANGE `description` `description` LONGTEXT NULL;
ALTER TABLE `#__redshop_category` CHANGE `more_template` `more_template` VARCHAR(255) NULL;
ALTER TABLE `#__redshop_category` CHANGE `category_thumb_image` `category_thumb_image` VARCHAR(250) NULL;
ALTER TABLE `#__redshop_category` CHANGE `category_full_image` `category_full_image` VARCHAR(250) NULL;
ALTER TABLE `#__redshop_category` CHANGE `metakey` `metakey` VARCHAR(250) NULL;
ALTER TABLE `#__redshop_category` CHANGE `metadesc` `metadesc` LONGTEXT NULL;
ALTER TABLE `#__redshop_category` CHANGE `metalanguage_setting` `metalanguage_setting` TEXT NULL;
ALTER TABLE `#__redshop_category` CHANGE `metarobot_info` `metarobot_info` TEXT NULL;
ALTER TABLE `#__redshop_category` CHANGE `pagetitle` `pagetitle` TEXT NULL;
ALTER TABLE `#__redshop_category` CHANGE `pageheading` `pageheading` LONGTEXT NULL;
ALTER TABLE `#__redshop_category` CHANGE `sef_url` `sef_url` TEXT NULL;
ALTER TABLE `#__redshop_category` CHANGE `ordering` `ordering` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_category` CHANGE `canonical_url` `canonical_url` TEXT NULL;
ALTER TABLE `#__redshop_category` CHANGE `category_back_full_image` `category_back_full_image` VARCHAR(250) NULL;
ALTER TABLE `#__redshop_category` CHANGE `compare_template_id` `compare_template_id` VARCHAR(255) NULL;
ALTER TABLE `#__redshop_category` CHANGE `alias` `alias` VARCHAR(255) NULL;
ALTER TABLE `#__redshop_category` CHANGE `path` `path` VARCHAR(255) NULL;
ALTER TABLE `#__redshop_category` CHANGE `product_filter_params` `product_filter_params` MEDIUMTEXT NULL;
ALTER TABLE `#__redshop_product` CHANGE `product_parent_id` `product_parent_id` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `product_download` `product_download` TINYINT(4) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `discount_stratdate` `discount_stratdate` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `discount_enddate` `discount_enddate` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `product_tax_id` `product_tax_id` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `product_thumb_image` `product_thumb_image` VARCHAR(250) NULL DEFAULT NULL;
ALTER TABLE `#__redshop_product` CHANGE `product_full_image` `product_full_image` VARCHAR(250) NULL DEFAULT NULL;
ALTER TABLE `#__redshop_product` CHANGE `attribute_set_id` `attribute_set_id` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `product_availability_date` `product_availability_date` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `product_tax_group_id` `product_tax_group_id` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `product_download_days` `product_download_days` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `product_download_limit` `product_download_limit` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `product_download_clock` `product_download_clock` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `product_download_clock_min` `product_download_clock_min` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `accountgroup_id` `accountgroup_id` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `quantity_selectbox_value` `quantity_selectbox_value` VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE `#__redshop_product` CHANGE `checked_out` `checked_out` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `checked_out_time` `checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00';
ALTER TABLE `#__redshop_product` CHANGE `max_order_product_quantity` `max_order_product_quantity` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `product_download_infinite` `product_download_infinite` TINYINT(4) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_manufacturer` CHANGE `description` `description` TEXT NOT NULL;
ALTER TABLE `#__redshop_manufacturer` CHANGE `metakey` `metakey` TEXT NOT NULL;
ALTER TABLE `#__redshop_manufacturer` CHANGE `metadesc` `metadesc` TEXT NOT NULL;
ALTER TABLE `#__redshop_manufacturer` CHANGE `metalanguage_setting` `metalanguage_setting` TEXT NOT NULL;
ALTER TABLE `#__redshop_manufacturer` CHANGE `metarobot_info` `metarobot_info` TEXT NOT NULL;
ALTER TABLE `#__redshop_manufacturer` CHANGE `pagetitle` `pagetitle` TEXT NOT NULL;
ALTER TABLE `#__redshop_manufacturer` CHANGE `pageheading` `pageheading` TEXT NOT NULL;
ALTER TABLE `#__redshop_manufacturer` CHANGE `sef_url` `sef_url` TEXT NOT NULL;
ALTER TABLE `#__redshop_manufacturer` CHANGE `excluding_category_list` `excluding_category_list` TEXT NOT NULL;
ALTER TABLE `#__redshop_mass_discount` CHANGE `discount_product` `discount_product` LONGTEXT NOT NULL;
ALTER TABLE `#__redshop_mass_discount` CHANGE `category_id` `category_id` LONGTEXT NOT NULL;
ALTER TABLE `#__redshop_mass_discount` CHANGE `manufacturer_id` `manufacturer_id` LONGTEXT NOT NULL;
ALTER TABLE `#__redshop_supplier` CHANGE `description` `description` TEXT NOT NULL;
ALTER TABLE `#__redshop_textlibrary` CHANGE `content` `content` TEXT NOT NULL;

ALTER TABLE `#__redshop_users_info` CHANGE `vat_number` `vat_number` VARCHAR(250) NULL;
ALTER TABLE `#__redshop_users_info` CHANGE `country_code` `country_code` VARCHAR(11) NULL;
ALTER TABLE `#__redshop_users_info` CHANGE `state_code` `state_code` VARCHAR(11) NULL;
ALTER TABLE `#__redshop_users_info` CHANGE `ean_number` `ean_number` VARCHAR(250) NULL;
ALTER TABLE `#__redshop_users_info` CHANGE `braintree_vault_number` `braintree_vault_number` VARCHAR(255) NULL;
ALTER TABLE `#__redshop_users_info` CHANGE `veis_vat_number` `veis_vat_number` VARCHAR(255) NULL;
ALTER TABLE `#__redshop_users_info` CHANGE `veis_status` `veis_status` VARCHAR(255) NULL;
ALTER TABLE `#__redshop_users_info` CHANGE `company_name` `company_name` VARCHAR(255) NULL;
ALTER TABLE `#__redshop_users_info` CHANGE `requesting_tax_exempt` `requesting_tax_exempt` TINYINT(4) NOT NULL DEFAULT '0';
