ALTER TABLE `#__redshop_category` CHANGE `short_description` `short_description` LONGTEXT;
ALTER TABLE `#__redshop_category` CHANGE `description` `description` LONGTEXT;
ALTER TABLE `#__redshop_category` CHANGE `more_template` `more_template` VARCHAR(255)  NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_category` CHANGE `category_thumb_image` `category_thumb_image` VARCHAR(250)  NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_category` CHANGE `category_full_image` `category_full_image` VARCHAR(250)  NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_category` CHANGE `metakey` `metakey` VARCHAR(250)  NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_category` CHANGE `name` `name` VARCHAR(250)  NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_category` CHANGE `metadesc` `metadesc` LONGTEXT;
ALTER TABLE `#__redshop_category` CHANGE `metalanguage_setting` `metalanguage_setting` TEXT;
ALTER TABLE `#__redshop_category` CHANGE `metarobot_info` `metarobot_info` TEXT;
ALTER TABLE `#__redshop_category` CHANGE `pagetitle` `pagetitle` TEXT;
ALTER TABLE `#__redshop_category` CHANGE `pageheading` `pageheading` LONGTEXT;
ALTER TABLE `#__redshop_category` CHANGE `sef_url` `sef_url` TEXT;
ALTER TABLE `#__redshop_category` CHANGE `ordering` `ordering` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_category` CHANGE `products_per_page` `products_per_page` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_category` CHANGE `template` `template` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_category` CHANGE `published` `published` TINYINT(4) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_category` CHANGE `canonical_url` `canonical_url` TEXT;
ALTER TABLE `#__redshop_category` CHANGE `category_back_full_image` `category_back_full_image` VARCHAR(250) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_category` CHANGE `compare_template_id` `compare_template_id` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_category` CHANGE `alias` `alias` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_category` CHANGE `path` `path` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_category` CHANGE `product_filter_params` `product_filter_params` MEDIUMTEXT;

ALTER TABLE `#__redshop_product` CHANGE `product_parent_id` `product_parent_id` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `manufacturer_id` `manufacturer_id` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `supplier_id` `supplier_id` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `product_on_sale` `product_on_sale` TINYINT(4) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `product_special` `product_special` TINYINT(4) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `product_download` `product_download` TINYINT(4) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `product_template` `product_template` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `product_name` `product_name` VARCHAR(250) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_product` CHANGE `product_price` `product_price` DOUBLE NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `discount_price` `discount_price` DOUBLE NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `discount_stratdate` `discount_stratdate` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `discount_enddate` `discount_enddate` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `product_number` `product_number` VARCHAR(250) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_product` CHANGE `product_type` `product_type` VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_product` CHANGE `product_s_desc` `product_s_desc` LONGTEXT;
ALTER TABLE `#__redshop_product` CHANGE `product_desc` `product_desc` LONGTEXT;
ALTER TABLE `#__redshop_product` CHANGE `product_volume` `product_volume` DOUBLE NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `product_tax_id` `product_tax_id` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `published` `published` TINYINT(4) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `product_thumb_image` `product_thumb_image` VARCHAR(250) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_product` CHANGE `product_full_image` `product_full_image` VARCHAR(250) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_product` CHANGE `publish_date` `publish_date` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00';
ALTER TABLE `#__redshop_product` CHANGE `update_date` `update_date` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT '0000-00-00 00:00:00';
ALTER TABLE `#__redshop_product` CHANGE `visited` `visited` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `metakey` `metakey` TEXT;
ALTER TABLE `#__redshop_product` CHANGE `metadesc` `metadesc` TEXT;
ALTER TABLE `#__redshop_product` CHANGE `metalanguage_setting` `metalanguage_setting` TEXT;
ALTER TABLE `#__redshop_product` CHANGE `metarobot_info` `metarobot_info` TEXT;
ALTER TABLE `#__redshop_product` CHANGE `pagetitle` `pagetitle` TEXT;
ALTER TABLE `#__redshop_product` CHANGE `pageheading` `pageheading` TEXT;
ALTER TABLE `#__redshop_product` CHANGE `sef_url` `sef_url` TEXT;
ALTER TABLE `#__redshop_product` CHANGE `cat_in_sefurl` `cat_in_sefurl` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `weight` `weight` FLOAT(10,3) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `expired` `expired` TINYINT(4) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `not_for_sale` `not_for_sale` TINYINT(4) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `use_discount_calc` `use_discount_calc` TINYINT(4) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `discount_calc_method` `discount_calc_method` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_product` CHANGE `min_order_product_quantity` `min_order_product_quantity` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `attribute_set_id` `attribute_set_id` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `product_length` `product_length` DECIMAL(10,2) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `product_height` `product_height` DECIMAL(10,2) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `product_width` `product_width` DECIMAL(10,2) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `product_diameter` `product_diameter` DECIMAL(10,2) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `product_availability_date` `product_availability_date` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `use_range` `use_range` TINYINT(4) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `product_tax_group_id` `product_tax_group_id` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `product_download_days` `product_download_days` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `product_download_limit` `product_download_limit` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `product_download_clock` `product_download_clock` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `product_download_clock_min` `product_download_clock_min` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `accountgroup_id` `accountgroup_id` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `canonical_url` `canonical_url` TEXT;
ALTER TABLE `#__redshop_product` CHANGE `minimum_per_product_total` `minimum_per_product_total` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `allow_decimal_piece` `allow_decimal_piece` INT(4) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `quantity_selectbox_value` `quantity_selectbox_value` VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE `#__redshop_product` CHANGE `checked_out` `checked_out` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `checked_out_time` `checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00';
ALTER TABLE `#__redshop_product` CHANGE `max_order_product_quantity` `max_order_product_quantity` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `product_download_infinite` `product_download_infinite` TINYINT(4) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_product` CHANGE `product_back_full_image` `product_back_full_image` VARCHAR(250) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_product` CHANGE `product_back_thumb_image` `product_back_thumb_image` VARCHAR(250) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_product` CHANGE `product_preview_image` `product_preview_image` VARCHAR(250) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_product` CHANGE `product_preview_back_image` `product_preview_back_image` VARCHAR(250) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_product` CHANGE `preorder` `preorder` VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE `#__redshop_manufacturer` CHANGE `description` `description` TEXT;
ALTER TABLE `#__redshop_manufacturer` CHANGE `template_id` `template_id` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_manufacturer` CHANGE `metakey` `metakey` TEXT;
ALTER TABLE `#__redshop_manufacturer` CHANGE `metadesc` `metadesc` TEXT;
ALTER TABLE `#__redshop_manufacturer` CHANGE `metalanguage_setting` `metalanguage_setting` TEXT;
ALTER TABLE `#__redshop_manufacturer` CHANGE `metarobot_info` `metarobot_info` TEXT;
ALTER TABLE `#__redshop_manufacturer` CHANGE `pagetitle` `pagetitle` TEXT;
ALTER TABLE `#__redshop_manufacturer` CHANGE `pageheading` `pageheading` TEXT;
ALTER TABLE `#__redshop_manufacturer` CHANGE `sef_url` `sef_url` TEXT;
ALTER TABLE `#__redshop_manufacturer` CHANGE `excluding_category_list` `excluding_category_list` TEXT;

ALTER TABLE `#__redshop_mass_discount` CHANGE `discount_product` `discount_product` LONGTEXT;
ALTER TABLE `#__redshop_mass_discount` CHANGE `category_id` `category_id` LONGTEXT;
ALTER TABLE `#__redshop_mass_discount` CHANGE `manufacturer_id` `manufacturer_id` LONGTEXT;
ALTER TABLE `#__redshop_mass_discount` CHANGE `type` `type` TINYINT(4) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_mass_discount` CHANGE `amount` `amount` DOUBLE(10,2) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_mass_discount` CHANGE `start_date` `start_date` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_mass_discount` CHANGE `end_date` `end_date` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_mass_discount` CHANGE `name` `name` VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE `#__redshop_supplier` CHANGE `description` `description` TEXT;

ALTER TABLE `#__redshop_textlibrary` CHANGE `content` `content` TEXT;
ALTER TABLE `#__redshop_textlibrary` CHANGE `section` `section` VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE `#__redshop_users_info` CHANGE `user_id` `user_id` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_users_info` CHANGE `user_email` `user_email` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_users_info` CHANGE `address_type` `address_type` VARCHAR(11) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_users_info` CHANGE `firstname` `firstname` VARCHAR(250) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_users_info` CHANGE `lastname` `lastname` VARCHAR(250) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_users_info` CHANGE `vat_number` `vat_number` VARCHAR(250) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_users_info` CHANGE `tax_exempt` `tax_exempt` TINYINT(4) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_users_info` CHANGE `shopper_group_id` `shopper_group_id` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_users_info` CHANGE `country_code` `country_code` VARCHAR(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_users_info` CHANGE `address` `address` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_users_info` CHANGE `city` `city` VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_users_info` CHANGE `state_code` `state_code` VARCHAR(11) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_users_info` CHANGE `zipcode` `zipcode` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_users_info` CHANGE `phone` `phone` VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_users_info` CHANGE `tax_exempt_approved` `tax_exempt_approved` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_users_info` CHANGE `approved` `approved` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_users_info` CHANGE `is_company` `is_company` TINYINT(4) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_users_info` CHANGE `ean_number` `ean_number` VARCHAR(250) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_users_info` CHANGE `braintree_vault_number` `braintree_vault_number` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_users_info` CHANGE `veis_vat_number` `veis_vat_number` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_users_info` CHANGE `veis_status` `veis_status` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_users_info` CHANGE `company_name` `company_name` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_users_info` CHANGE `requesting_tax_exempt` `requesting_tax_exempt` TINYINT(4) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_users_info` CHANGE `accept_terms_conditions` `accept_terms_conditions` TINYINT(4) NOT NULL DEFAULT 0;

ALTER TABLE `#__redshop_product_attribute_property` CHANGE `property_name` `property_name` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_product_attribute_property` CHANGE `property_price` `property_price` DOUBLE NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_product_attribute_property` CHANGE `property_image` `property_image` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_product_attribute_property` CHANGE `property_main_image` `property_main_image` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_product_attribute_property` CHANGE `ordering` `ordering` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_product_attribute_property` CHANGE `setdefault_selected` `setdefault_selected` TINYINT(4) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_product_attribute_property` CHANGE `setrequire_selected` `setrequire_selected` TINYINT(3) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_product_attribute_property` CHANGE `setmulti_selected` `setmulti_selected` TINYINT(4) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_product_attribute_property` CHANGE `setdisplay_type` `setdisplay_type` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_product_attribute_property` CHANGE `extra_field` `extra_field` VARCHAR(250) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_product_attribute_property` CHANGE `property_number` `property_number` VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE `#__redshop_product_subattribute_color` CHANGE `subattribute_color_name` `subattribute_color_name` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_product_subattribute_color` CHANGE `subattribute_color_price` `subattribute_color_price` DOUBLE NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_product_subattribute_color` CHANGE `oprand` `oprand` CHAR(1) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_product_subattribute_color` CHANGE `subattribute_color_image` `subattribute_color_image` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_product_subattribute_color` CHANGE `subattribute_id` `subattribute_id` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_product_subattribute_color` CHANGE `ordering` `ordering` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_product_subattribute_color` CHANGE `setdefault_selected` `setdefault_selected` TINYINT(4) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_product_subattribute_color` CHANGE `extra_field` `extra_field` VARCHAR(250) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_product_subattribute_color` CHANGE `subattribute_color_number` `subattribute_color_number` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_product_subattribute_color` CHANGE `subattribute_color_title` `subattribute_color_title` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_product_subattribute_color` CHANGE `subattribute_color_main_image` `subattribute_color_main_image` VARCHAR(255) NULL DEFAULT '';

ALTER TABLE `#__redshop_media` CHANGE `media_name` `media_name` VARCHAR(250) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_media` CHANGE `media_alternate_text` `media_alternate_text` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_media` CHANGE `media_section` `media_section` VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_media` CHANGE `section_id` `section_id` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_media` CHANGE `media_type` `media_type` VARCHAR(250) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_media` CHANGE `media_mimetype` `media_mimetype` VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_media` CHANGE `published` `published` TINYINT(4) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_media` CHANGE `ordering` `ordering` INT(11) NOT NULL DEFAULT '0';

ALTER TABLE `#__redshop_orders` CHANGE `invoice_number_chrono` `invoice_number_chrono` INT(11) NOT NULL DEFAULT 0 COMMENT 'Order invoice number in chronological order';
ALTER TABLE `#__redshop_orders` CHANGE `invoice_number` `invoice_number` VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'Formatted Order Invoice for final use';
ALTER TABLE `#__redshop_orders` CHANGE `barcode` `barcode` VARCHAR(13) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_orders` CHANGE `order_tax_details` `order_tax_details` TEXT;
ALTER TABLE `#__redshop_orders` CHANGE `special_discount_amount` `special_discount_amount` DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_orders` CHANGE `payment_dicount` `payment_dicount` DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_orders` CHANGE `order_payment_status` `order_payment_status` VARCHAR(25) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_orders` CHANGE `customer_note` `customer_note` TEXT;
ALTER TABLE `#__redshop_orders` CHANGE `encr_key` `encr_key` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_orders` CHANGE `invoice_no` `invoice_no` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_orders` CHANGE `mail1_status` `mail1_status` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_orders` CHANGE `mail2_status` `mail2_status` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_orders` CHANGE `mail3_status` `mail3_status` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_orders` CHANGE `special_discount` `special_discount` DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_orders` CHANGE `payment_discount` `payment_discount` DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_orders` CHANGE `is_booked` `is_booked` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_orders` CHANGE `order_label_create` `order_label_create` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_orders` CHANGE `vm_order_number` `vm_order_number` VARCHAR(32) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_orders` CHANGE `requisition_number` `requisition_number` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_orders` CHANGE `bookinvoice_number` `bookinvoice_number` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_orders` CHANGE `bookinvoice_date` `bookinvoice_date` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_orders` CHANGE `referral_code` `referral_code` VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_orders` CHANGE `customer_message` `customer_message` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_orders` CHANGE `shop_id` `shop_id` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_orders` CHANGE `order_discount_vat` `order_discount_vat` DECIMAL(10,3) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_orders` CHANGE `track_no` `track_no` VARCHAR(250) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_orders` CHANGE `payment_oprand` `payment_oprand` VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_orders` CHANGE `discount_type` `discount_type` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_orders` CHANGE `analytics_status` `analytics_status` INT(1) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_orders` CHANGE `tax_after_discount` `tax_after_discount` DECIMAL(10,3) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_orders` CHANGE `recuuring_subcription_id` `recuuring_subcription_id` VARCHAR(500) NOT NULL DEFAULT '';

ALTER TABLE `#__redshop_order_item` CHANGE `order_item_name` `order_item_name` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_order_item` CHANGE `customer_note` `customer_note` TEXT;
ALTER TABLE `#__redshop_order_item` CHANGE `product_accessory` `product_accessory` TEXT;
ALTER TABLE `#__redshop_order_item` CHANGE `delivery_time` `delivery_time` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_order_item` CHANGE `stockroom_id` `stockroom_id` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_order_item` CHANGE `stockroom_quantity` `stockroom_quantity` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_order_item` CHANGE `is_split` `is_split` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_order_item` CHANGE `attribute_image` `attribute_image` TEXT;
ALTER TABLE `#__redshop_order_item` CHANGE `is_giftcard` `is_giftcard` TINYINT(4) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_order_item` CHANGE `wrapper_id` `wrapper_id` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_order_item` CHANGE `wrapper_price` `wrapper_price` DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_order_item` CHANGE `giftcard_user_name` `giftcard_user_name` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_order_item` CHANGE `giftcard_user_email` `giftcard_user_email` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_order_item` CHANGE `product_item_old_price` `product_item_old_price` DECIMAL(10,4) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_order_item` CHANGE `product_purchase_price` `product_purchase_price` DECIMAL(10,4) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_order_item` CHANGE `discount_calc_data` `discount_calc_data` TEXT;

ALTER TABLE `#__redshop_product_accessory` CHANGE `accessory_price` `accessory_price` DOUBLE NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_product_accessory` CHANGE `oprand` `oprand` CHAR(1) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_product_accessory` CHANGE `setdefault_selected` `setdefault_selected` TINYINT(4) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_product_accessory` CHANGE `ordering` `ordering` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_product_accessory` CHANGE `category_id` `category_id` INT(11) NOT NULL DEFAULT 0;

ALTER TABLE `#__redshop_fields` CHANGE `title` `title` VARCHAR(250) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_fields` CHANGE `name` `name` VARCHAR(250) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_fields` CHANGE `desc` `desc` LONGTEXT;
ALTER TABLE `#__redshop_fields` CHANGE `class` `class` VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_fields` CHANGE `section` `section` VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_fields` CHANGE `maxlength` `maxlength` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_fields` CHANGE `cols` `cols` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_fields` CHANGE `rows` `rows` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_fields` CHANGE `size` `size` TINYINT(4) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_fields` CHANGE `show_in_front` `show_in_front` TINYINT(4) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_fields` CHANGE `required` `required` TINYINT(4) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_fields` CHANGE `published` `published` TINYINT(4) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_fields` CHANGE `display_in_product` `display_in_product` TINYINT(4) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_fields` CHANGE `ordering` `ordering` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_fields` CHANGE `display_in_checkout` `display_in_checkout` TINYINT(4) NOT NULL DEFAULT 0;

ALTER TABLE `#__redshop_fields_data` CHANGE `alt_text` `alt_text` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_fields_data` CHANGE `image_link` `image_link` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_fields_data` CHANGE `user_email` `user_email` VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE `#__redshop_product_rating` CHANGE `favoured` `favoured` TINYINT(4) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_product_rating` CHANGE `published` `published` TINYINT(4) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_product_rating` CHANGE `email` `email` VARCHAR(200) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_product_rating` CHANGE `username` `username` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_product_rating` CHANGE `company_name` `company_name` VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE `#__redshop_tax_rate` CHANGE `tax_group_id` `tax_group_id` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_tax_rate` CHANGE `shopper_group_id` `shopper_group_id` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_tax_rate` CHANGE `is_eu_country` `is_eu_country` TINYINT(4) NOT NULL DEFAULT 0;

ALTER TABLE `#__redshop_order_payment` CHANGE `order_payment_cardname` `order_payment_cardname` BLOB NULL DEFAULT NULL;
ALTER TABLE `#__redshop_order_payment` CHANGE `order_payment_ccv` `order_payment_ccv` BLOB NULL DEFAULT NULL;
ALTER TABLE `#__redshop_order_payment` CHANGE `order_payment_amount` `order_payment_amount` DOUBLE(10,2) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_order_payment` CHANGE `order_payment_trans_id` `order_payment_trans_id` TEXT;
ALTER TABLE `#__redshop_order_payment` CHANGE `order_transfee` `order_transfee` DOUBLE(10,2) NOT NULL DEFAULT 0;

ALTER TABLE `#__redshop_order_users_info` CHANGE `users_info_id` `users_info_id` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_order_users_info` CHANGE `user_id` `user_id` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_order_users_info` CHANGE `firstname` `firstname` VARCHAR(250) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_order_users_info` CHANGE `lastname` `lastname` VARCHAR(250) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_order_users_info` CHANGE `address_type` `address_type` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_order_users_info` CHANGE `vat_number` `vat_number` VARCHAR(250) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_order_users_info` CHANGE `tax_exempt` `tax_exempt` TINYINT(4) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_order_users_info` CHANGE `shopper_group_id` `shopper_group_id` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_order_users_info` CHANGE `address` `address` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_order_users_info` CHANGE `city` `city` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_order_users_info` CHANGE `country_code` `country_code` VARCHAR(11) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_order_users_info` CHANGE `state_code` `state_code` VARCHAR(11) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_order_users_info` CHANGE `zipcode` `zipcode` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_order_users_info` CHANGE `phone` `phone` VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_order_users_info` CHANGE `tax_exempt_approved` `tax_exempt_approved` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_order_users_info` CHANGE `approved` `approved` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_order_users_info` CHANGE `is_company` `is_company` TINYINT(4) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_order_users_info` CHANGE `user_email` `user_email` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_order_users_info` CHANGE `company_name` `company_name` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_order_users_info` CHANGE `ean_number` `ean_number` VARCHAR(250) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_order_users_info` CHANGE `requesting_tax_exempt` `requesting_tax_exempt` TINYINT(4) NOT NULL DEFAULT 0;
ALTER TABLE `#__redshop_order_users_info` CHANGE `thirdparty_email` `thirdparty_email` VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE `#__redshop_shipping_rate` CHANGE `deliver_type` `deliver_type` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `#__redshop_shipping_rate` CHANGE `shipping_rate_weight_start` `shipping_rate_weight_start` DECIMAL(10,2) NOT NULL AFTER `apply_vat`

ALTER TABLE `#__redshop_order_attribute_item` CHANGE `section_price` `section_price` DECIMAL(15,4) NOT NULL DEFAULT '0.0000';
ALTER TABLE `#__redshop_order_attribute_item` CHANGE `section_vat` `section_vat` DECIMAL(15,4) NOT NULL DEFAULT '0.0000';
ALTER TABLE `#__redshop_order_attribute_item` CHANGE `section_oprand` `section_oprand` CHAR(1) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_order_attribute_item` CHANGE `stockroom_id` `stockroom_id` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `#__redshop_order_attribute_item` CHANGE `stockroom_quantity` `stockroom_quantity` VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE `#__redshop_product_discount_calc_extra` CHANGE `oprand` `oprand` CHAR(1) NOT NULL DEFAULT '';

ALTER TABLE `#__redshop_quotation_attribute_item` CHANGE `section_price` `section_price` DECIMAL(15,4) NOT NULL DEFAULT '0.0000';
ALTER TABLE `#__redshop_quotation_attribute_item` CHANGE `section_vat` `section_vat` DECIMAL(15,4) NOT NULL DEFAULT '0.0000';
ALTER TABLE `#__redshop_quotation_attribute_item` CHANGE `section_oprand` `section_oprand` CHAR(1) NOT NULL DEFAULT '';

ALTER TABLE `#__redshop_wishlist` CHANGE `comment` `comment` MEDIUMTEXT NOT NULL DEFAULT '';