<table border="0">
	<tbody>
	<tr>
		<td>{user_name_lbl}</td>
		<td>{user_name}</td>
	</tr>
	<tr>
		<td>{user_email_lbl}</td>
		<td>{user_email}</td>
	</tr>
	<tr>
		<td>{user_question_lbl}</td>
		<td>{user_question}</td>
	</tr>
	<tr>
		<td></td>
		<td>{send_button}</td>
	</tr>
	<tr>
		<td>{captcha_lbl}</td>
		<td>{captcha}</td>
	</tr>
	</tbody>
</table>
