<?php
defined('_JEXEC') or die;
define('UPS_Canada_ACCESS_CODE', 'EC6BF63E41F6BEA0');
define('UPS_Canada_USER_ID', 'mysibling2');
define('UPS_Canada_PASSWORD', 'dolls13');
define('UPS_Canada_PICKUP_TYPE', '01');
define('UPS_Canada_PACKAGE_TYPE', '02');
define('UPS_Canada_RESIDENTIAL', 'yes');
define('UPS_Canada_HANDLING_FEE', '0');
define('UPS_Canada_TAX_CLASS', '');
define('UPS_Canada_Override_Source_Zip', 'G0W 1G0');
define('UPS_Canada_Show_Delivery_Days_Quote', '');
define('UPS_Canada_Show_Delivery_ETA_Quote', '');
define('UPS_Canada_Show_Delivery_Warning', '');
define('UPS_Canada_Express', '01');
define('UPS_Canada_Express_FSC', '0.5');
define('UPS_Canada_Expedited', '02');
define('UPS_Canada_Expedited_FSC', '0.5');
define('UPS_Canada_Worldwide_Express', '07');
define('UPS_Canada_Worldwide_Express_FSC', '0.5');
define('UPS_Canada_Worldwide_Expedited', '08');
define('UPS_Canada_Worldwide_Expedited_FSC', '0.5');
define('UPS_Canada_Standard', '11');
define('UPS_Canada_Standard_FSC', '0.5');
define('UPS_Canada_ThreeDay_Select', '12');
define('UPS_Canada_ThreeDay_Select_FSC', '0.5');
define('UPS_Canada_Saver', '13');
define('UPS_Canada_Saver_FSC', '0.5');
define('UPS_Canada_Express_Early_AM', '14');
define('UPS_Canada_Express_Early_AM_FSC', '0.5');
define('UPS_Canada_Worldwide_Express_Plus', '54');
define('UPS_Canada_Worldwide_Express_Plus_FSC', '0.5');
define('UPS_Canada_Saver1', '65');
define('UPS_Canada_Saver1_FSC', '0.5');
define('UPS_Canada_na', '64');
