INSERT IGNORE INTO `#__redshop_country` (`id`, `country_name`, `country_3_code`, `country_2_code`) VALUES
	(1, 'Afghanistan', 'AFG', 'AF'),
	(2, 'Albania', 'ALB', 'AL'),
	(3, 'Algeria', 'DZA', 'DZ'),
	(4, 'American Samoa', 'ASM', 'AS'),
	(5, 'Andorra', 'AND', 'AD'),
	(6, 'Angola', 'AGO', 'AO'),
	(7, 'Anguilla', 'AIA', 'AI'),
	(8, 'Antarctica', 'ATA', 'AQ'),
	(9, 'Antigua and Barbuda', 'ATG', 'AG'),
	(10, 'Argentina', 'ARG', 'AR'),
	(11, 'Armenia', 'ARM', 'AM'),
	(12, 'Aruba', 'ABW', 'AW'),
	(13, 'Australia', 'AUS', 'AU'),
	(14, 'Austria', 'AUT', 'AT'),
	(15, 'Azerbaijan', 'AZE', 'AZ'),
	(16, 'Bahamas', 'BHS', 'BS'),
	(17, 'Bahrain', 'BHR', 'BH'),
	(18, 'Bangladesh', 'BGD', 'BD'),
	(19, 'Barbados', 'BRB', 'BB'),
	(20, 'Belarus', 'BLR', 'BY'),
	(21, 'Belgium', 'BEL', 'BE'),
	(22, 'Belize', 'BLZ', 'BZ'),
	(23, 'Benin', 'BEN', 'BJ'),
	(24, 'Bermuda', 'BMU', 'BM'),
	(25, 'Bhutan', 'BTN', 'BT'),
	(26, 'Bolivia', 'BOL', 'BO'),
	(27, 'Bosnia and Herzegowina', 'BIH', 'BA'),
	(28, 'Botswana', 'BWA', 'BW'),
	(29, 'Bouvet Island', 'BVT', 'BV'),
	(30, 'Brazil', 'BRA', 'BR'),
	(31, 'British Indian Ocean Territory', 'IOT', 'IO'),
	(32, 'Brunei Darussalam', 'BRN', 'BN'),
	(33, 'Bulgaria', 'BGR', 'BG'),
	(34, 'Burkina Faso', 'BFA', 'BF'),
	(35, 'Burundi', 'BDI', 'BI'),
	(36, 'Cambodia', 'KHM', 'KH'),
	(37, 'Cameroon', 'CMR', 'CM'),
	(38, 'Canada', 'CAN', 'CA'),
	(39, 'Cape Verde', 'CPV', 'CV'),
	(40, 'Cayman Islands', 'CYM', 'KY'),
	(41, 'Central African Republic', 'CAF', 'CF'),
	(42, 'Chad', 'TCD', 'TD'),
	(43, 'Chile', 'CHL', 'CL'),
	(44, 'China', 'CHN', 'CN'),
	(45, 'Christmas Island', 'CXR', 'CX'),
	(46, 'Cocos (Keeling) Islands', 'CCK', 'CC'),
	(47, 'Colombia', 'COL', 'CO'),
	(48, 'Comoros', 'COM', 'KM'),
	(49, 'Congo', 'COG', 'CG'),
	(50, 'Cook Islands', 'COK', 'CK'),
	(51, 'Costa Rica', 'CRI', 'CR'),
	(52, 'Cote D''Ivoire', 'CIV', 'CI'),
	(53, 'Croatia', 'HRV', 'HR'),
	(54, 'Cuba', 'CUB', 'CU'),
	(55, 'Cyprus', 'CYP', 'CY'),
	(56, 'Czech Republic', 'CZE', 'CZ'),
	(57, 'Denmark', 'DNK', 'DK'),
	(58, 'Djibouti', 'DJI', 'DJ'),
	(59, 'Dominica', 'DMA', 'DM'),
	(60, 'Dominican Republic', 'DOM', 'DO'),
	(62, 'Ecuador', 'ECU', 'EC'),
	(63, 'Egypt', 'EGY', 'EG'),
	(64, 'El Salvador', 'SLV', 'SV'),
	(65, 'Equatorial Guinea', 'GNQ', 'GQ'),
	(66, 'Eritrea', 'ERI', 'ER'),
	(67, 'Estonia', 'EST', 'EE'),
	(68, 'Ethiopia', 'ETH', 'ET'),
	(69, 'Falkland Islands (Malvinas)', 'FLK', 'FK'),
	(70, 'Faroe Islands', 'FRO', 'FO'),
	(71, 'Fiji', 'FJI', 'FJ'),
	(72, 'Finland', 'FIN', 'FI'),
	(73, 'France', 'FRA', 'FR'),
	(75, 'French Guiana', 'GUF', 'GF'),
	(76, 'French Polynesia', 'PYF', 'PF'),
	(77, 'French Southern Territories', 'ATF', 'TF'),
	(78, 'Gabon', 'GAB', 'GA'),
	(79, 'Gambia', 'GMB', 'GM'),
	(80, 'Georgia', 'GEO', 'GE'),
	(81, 'Germany', 'DEU', 'DE'),
	(82, 'Ghana', 'GHA', 'GH'),
	(83, 'Gibraltar', 'GIB', 'GI'),
	(84, 'Greece', 'GRC', 'GR'),
	(85, 'Greenland', 'GRL', 'GL'),
	(86, 'Grenada', 'GRD', 'GD'),
	(87, 'Guadeloupe', 'GLP', 'GP'),
	(88, 'Guam', 'GUM', 'GU'),
	(89, 'Guatemala', 'GTM', 'GT'),
	(90, 'Guinea', 'GIN', 'GN'),
	(91, 'Guinea-bissau', 'GNB', 'GW'),
	(92, 'Guyana', 'GUY', 'GY'),
	(93, 'Haiti', 'HTI', 'HT'),
	(94, 'Heard and Mc Donald Islands', 'HMD', 'HM'),
	(95, 'Honduras', 'HND', 'HN'),
	(96, 'Hong Kong', 'HKG', 'HK'),
	(97, 'Hungary', 'HUN', 'HU'),
	(98, 'Iceland', 'ISL', 'IS'),
	(99, 'India', 'IND', 'IN'),
	(100, 'Indonesia', 'IDN', 'ID'),
	(101, 'Iran (Islamic Republic of)', 'IRN', 'IR'),
	(102, 'Iraq', 'IRQ', 'IQ'),
	(103, 'Ireland', 'IRL', 'IE'),
	(104, 'Israel', 'ISR', 'IL'),
	(105, 'Italy', 'ITA', 'IT'),
	(106, 'Jamaica', 'JAM', 'JM'),
	(107, 'Japan', 'JPN', 'JP'),
	(108, 'Jordan', 'JOR', 'JO'),
	(109, 'Kazakhstan', 'KAZ', 'KZ'),
	(110, 'Kenya', 'KEN', 'KE'),
	(111, 'Kiribati', 'KIR', 'KI'),
	(112, 'Korea, Democratic People''s Republic of', 'PRK', 'KP'),
	(113, 'Korea, Republic of', 'KOR', 'KR'),
	(114, 'Kuwait', 'KWT', 'KW'),
	(115, 'Kyrgyzstan', 'KGZ', 'KG'),
	(116, 'Lao People''s Democratic Republic', 'LAO', 'LA'),
	(117, 'Latvia', 'LVA', 'LV'),
	(118, 'Lebanon', 'LBN', 'LB'),
	(119, 'Lesotho', 'LSO', 'LS'),
	(120, 'Liberia', 'LBR', 'LR'),
	(121, 'Libyan Arab Jamahiriya', 'LBY', 'LY'),
	(122, 'Liechtenstein', 'LIE', 'LI'),
	(123, 'Lithuania', 'LTU', 'LT'),
	(124, 'Luxembourg', 'LUX', 'LU'),
	(125, 'Macau', 'MAC', 'MO'),
	(126, 'Macedonia, The Former Yugoslav Republic of', 'MKD', 'MK'),
	(127, 'Madagascar', 'MDG', 'MG'),
	(128, 'Malawi', 'MWI', 'MW'),
	(129, 'Malaysia', 'MYS', 'MY'),
	(130, 'Maldives', 'MDV', 'MV'),
	(131, 'Mali', 'MLI', 'ML'),
	(132, 'Malta', 'MLT', 'MT'),
	(133, 'Marshall Islands', 'MHL', 'MH'),
	(134, 'Martinique', 'MTQ', 'MQ'),
	(135, 'Mauritania', 'MRT', 'MR'),
	(136, 'Mauritius', 'MUS', 'MU'),
	(137, 'Mayotte', 'MYT', 'YT'),
	(138, 'Mexico', 'MEX', 'MX'),
	(139, 'Micronesia, Federated States of', 'FSM', 'FM'),
	(140, 'Moldova, Republic of', 'MDA', 'MD'),
	(141, 'Monaco', 'MCO', 'MC'),
	(142, 'Mongolia', 'MNG', 'MN'),
	(143, 'Montserrat', 'MSR', 'MS'),
	(144, 'Morocco', 'MAR', 'MA'),
	(145, 'Mozambique', 'MOZ', 'MZ'),
	(146, 'Myanmar', 'MMR', 'MM'),
	(147, 'Namibia', 'NAM', 'NA'),
	(148, 'Nauru', 'NRU', 'NR'),
	(149, 'Nepal', 'NPL', 'NP'),
	(150, 'Netherlands', 'NLD', 'NL'),
	(151, 'Netherlands Antilles', 'ANT', 'AN'),
	(152, 'New Caledonia', 'NCL', 'NC'),
	(153, 'New Zealand', 'NZL', 'NZ'),
	(154, 'Nicaragua', 'NIC', 'NI'),
	(155, 'Niger', 'NER', 'NE'),
	(156, 'Nigeria', 'NGA', 'NG'),
	(157, 'Niue', 'NIU', 'NU'),
	(158, 'Norfolk Island', 'NFK', 'NF'),
	(159, 'Northern Mariana Islands', 'MNP', 'MP'),
	(160, 'Norway', 'NOR', 'NO'),
	(161, 'Oman', 'OMN', 'OM'),
	(162, 'Pakistan', 'PAK', 'PK'),
	(163, 'Palau', 'PLW', 'PW'),
	(164, 'Panama', 'PAN', 'PA'),
	(165, 'Papua New Guinea', 'PNG', 'PG'),
	(166, 'Paraguay', 'PRY', 'PY'),
	(167, 'Peru', 'PER', 'PE'),
	(168, 'Philippines', 'PHL', 'PH'),
	(169, 'Pitcairn', 'PCN', 'PN'),
	(170, 'Poland', 'POL', 'PL'),
	(171, 'Portugal', 'PRT', 'PT'),
	(172, 'Puerto Rico', 'PRI', 'PR'),
	(173, 'Qatar', 'QAT', 'QA'),
	(174, 'Reunion', 'REU', 'RE'),
	(175, 'Romania', 'ROM', 'RO'),
	(176, 'Russian Federation', 'RUS', 'RU'),
	(177, 'Rwanda', 'RWA', 'RW'),
	(178, 'Saint Kitts and Nevis', 'KNA', 'KN'),
	(179, 'Saint Lucia', 'LCA', 'LC'),
	(180, 'Saint Vincent and the Grenadines', 'VCT', 'VC'),
	(181, 'Samoa', 'WSM', 'WS'),
	(182, 'San Marino', 'SMR', 'SM'),
	(183, 'Sao Tome and Principe', 'STP', 'ST'),
	(184, 'Saudi Arabia', 'SAU', 'SA'),
	(185, 'Senegal', 'SEN', 'SN'),
	(186, 'Seychelles', 'SYC', 'SC'),
	(187, 'Sierra Leone', 'SLE', 'SL'),
	(188, 'Singapore', 'SGP', 'SG'),
	(189, 'Slovakia (Slovak Republic)', 'SVK', 'SK'),
	(190, 'Slovenia', 'SVN', 'SI'),
	(191, 'Solomon Islands', 'SLB', 'SB'),
	(192, 'Somalia', 'SOM', 'SO'),
	(193, 'South Africa', 'ZAF', 'ZA'),
	(194, 'South Georgia and the South Sandwich Islands', 'SGS', 'GS'),
	(195, 'Spain', 'ESP', 'ES'),
	(196, 'Sri Lanka', 'LKA', 'LK'),
	(197, 'St. Helena', 'SHN', 'SH'),
	(198, 'St. Pierre and Miquelon', 'SPM', 'PM'),
	(199, 'Sudan', 'SDN', 'SD'),
	(200, 'Suriname', 'SUR', 'SR'),
	(201, 'Svalbard and Jan Mayen Islands', 'SJM', 'SJ'),
	(202, 'Swaziland', 'SWZ', 'SZ'),
	(203, 'Sweden', 'SWE', 'SE'),
	(204, 'Switzerland', 'CHE', 'CH'),
	(205, 'Syrian Arab Republic', 'SYR', 'SY'),
	(206, 'Taiwan', 'TWN', 'TW'),
	(207, 'Tajikistan', 'TJK', 'TJ'),
	(208, 'Tanzania, United Republic of', 'TZA', 'TZ'),
	(209, 'Thailand', 'THA', 'TH'),
	(210, 'Togo', 'TGO', 'TG'),
	(211, 'Tokelau', 'TKL', 'TK'),
	(212, 'Tonga', 'TON', 'TO'),
	(213, 'Trinidad and Tobago', 'TTO', 'TT'),
	(214, 'Tunisia', 'TUN', 'TN'),
	(215, 'Turkey', 'TUR', 'TR'),
	(216, 'Turkmenistan', 'TKM', 'TM'),
	(217, 'Turks and Caicos Islands', 'TCA', 'TC'),
	(218, 'Tuvalu', 'TUV', 'TV'),
	(219, 'Uganda', 'UGA', 'UG'),
	(220, 'Ukraine', 'UKR', 'UA'),
	(221, 'United Arab Emirates', 'ARE', 'AE'),
	(222, 'United Kingdom', 'GBR', 'GB'),
	(223, 'United States', 'USA', 'US'),
	(224, 'United States Minor Outlying Islands', 'UMI', 'UM'),
	(225, 'Uruguay', 'URY', 'UY'),
	(226, 'Uzbekistan', 'UZB', 'UZ'),
	(227, 'Vanuatu', 'VUT', 'VU'),
	(228, 'Vatican City State (Holy See)', 'VAT', 'VA'),
	(229, 'Venezuela', 'VEN', 'VE'),
	(230, 'Viet Nam', 'VNM', 'VN'),
	(231, 'Virgin Islands (British)', 'VGB', 'VG'),
	(232, 'Virgin Islands (U.S.)', 'VIR', 'VI'),
	(233, 'Wallis and Futuna Islands', 'WLF', 'WF'),
	(234, 'Western Sahara', 'ESH', 'EH'),
	(235, 'Yemen', 'YEM', 'YE'),
	(237, 'The Democratic Republic of Congo', 'DRC', 'DC'),
	(238, 'Zambia', 'ZMB', 'ZM'),
	(239, 'Zimbabwe', 'ZWE', 'ZW'),
	(241, 'Jersey', 'XJE', 'XJ'),
	(242, 'St. Barthelemy', 'XSB', 'XB'),
	(245, 'Aland Islands', 'ALA', 'AX'),
	(246, 'Guernsey', 'GGY', 'GG'),
	(247, 'Saint Martin (French part)', 'MAF', 'MF'),
	(248, 'Timor-Leste', 'TLS', 'TL'),
	(249, 'Serbia', 'SRB', 'RS'),
	(250, 'Isle of Man', 'IMN', 'IM'),
	(251, 'Montenegro', 'MNE', 'ME'),
	(252, 'Palestinian Territory, Occupied', 'PSE', 'PS');

INSERT IGNORE INTO `#__redshop_cron` (`id`, `date`, `published`) VALUES
	(1, '2009-08-12', 1);

INSERT IGNORE INTO `#__redshop_currency` (`currency_id`, `currency_name`, `currency_code`) VALUES
	(1, 'Andorran Peseta', 'ADP'),
	(2, 'United Arab Emirates Dirham', 'AED'),
	(3, 'Afghanistan Afghani', 'AFA'),
	(4, 'Albanian Lek', 'ALL'),
	(5, 'Netherlands Antillian Guilder', 'ANG'),
	(6, 'Angolan Kwanza', 'AOK'),
	(7, 'Argentine Peso', 'ARS'),
	(9, 'Australian Dollar', 'AUD'),
	(10, 'Aruban Florin', 'AWG'),
	(11, 'Barbados Dollar', 'BBD'),
	(12, 'Bangladeshi Taka', 'BDT'),
	(14, 'Bulgarian Lev', 'BGL'),
	(15, 'Bahraini Dinar', 'BHD'),
	(16, 'Burundi Franc', 'BIF'),
	(17, 'Bermudian Dollar', 'BMD'),
	(18, 'Brunei Dollar', 'BND'),
	(19, 'Bolivian Boliviano', 'BOB'),
	(20, 'Brazilian Real', 'BRL'),
	(21, 'Bahamian Dollar', 'BSD'),
	(22, 'Bhutan Ngultrum', 'BTN'),
	(23, 'Burma Kyat', 'BUK'),
	(24, 'Botswanian Pula', 'BWP'),
	(25, 'Belize Dollar', 'BZD'),
	(26, 'Canadian Dollar', 'CAD'),
	(27, 'Swiss Franc', 'CHF'),
	(28, 'Chilean Unidades de Fomento', 'CLF'),
	(29, 'Chilean Peso', 'CLP'),
	(30, 'Yuan (Chinese) Renminbi', 'CNY'),
	(31, 'Colombian Peso', 'COP'),
	(32, 'Costa Rican Colon', 'CRC'),
	(33, 'Czech Koruna', 'CZK'),
	(34, 'Cuban Peso', 'CUP'),
	(35, 'Cape Verde Escudo', 'CVE'),
	(36, 'Cyprus Pound', 'CYP'),
	(40, 'Danish Krone', 'DKK'),
	(41, 'Dominican Peso', 'DOP'),
	(42, 'Algerian Dinar', 'DZD'),
	(43, 'Ecuador Sucre', 'ECS'),
	(44, 'Egyptian Pound', 'EGP'),
	(46, 'Ethiopian Birr', 'ETB'),
	(47, 'Euro', 'EUR'),
	(49, 'Fiji Dollar', 'FJD'),
	(50, 'Falkland Islands Pound', 'FKP'),
	(52, 'British Pound', 'GBP'),
	(53, 'Ghanaian Cedi', 'GHC'),
	(54, 'Gibraltar Pound', 'GIP'),
	(55, 'Gambian Dalasi', 'GMD'),
	(56, 'Guinea Franc', 'GNF'),
	(58, 'Guatemalan Quetzal', 'GTQ'),
	(59, 'Guinea-Bissau Peso', 'GWP'),
	(60, 'Guyanan Dollar', 'GYD'),
	(61, 'Hong Kong Dollar', 'HKD'),
	(62, 'Honduran Lempira', 'HNL'),
	(63, 'Haitian Gourde', 'HTG'),
	(64, 'Hungarian Forint', 'HUF'),
	(65, 'Indonesian Rupiah', 'IDR'),
	(66, 'Irish Punt', 'IEP'),
	(67, 'Israeli Shekel', 'ILS'),
	(68, 'Indian Rupee', 'INR'),
	(69, 'Iraqi Dinar', 'IQD'),
	(70, 'Iranian Rial', 'IRR'),
	(73, 'Jamaican Dollar', 'JMD'),
	(74, 'Jordanian Dinar', 'JOD'),
	(75, 'Japanese Yen', 'JPY'),
	(76, 'Kenyan Schilling', 'KES'),
	(77, 'Kampuchean (Cambodian) Riel', 'KHR'),
	(78, 'Comoros Franc', 'KMF'),
	(79, 'North Korean Won', 'KPW'),
	(80, '(South) Korean Won', 'KRW'),
	(81, 'Kuwaiti Dinar', 'KWD'),
	(82, 'Cayman Islands Dollar', 'KYD'),
	(83, 'Lao Kip', 'LAK'),
	(84, 'Lebanese Pound', 'LBP'),
	(85, 'Sri Lanka Rupee', 'LKR'),
	(86, 'Liberian Dollar', 'LRD'),
	(87, 'Lesotho Loti', 'LSL'),
	(89, 'Libyan Dinar', 'LYD'),
	(90, 'Moroccan Dirham', 'MAD'),
	(91, 'Malagasy Franc', 'MGF'),
	(92, 'Mongolian Tugrik', 'MNT'),
	(93, 'Macau Pataca', 'MOP'),
	(94, 'Mauritanian Ouguiya', 'MRO'),
	(95, 'Maltese Lira', 'MTL'),
	(96, 'Mauritius Rupee', 'MUR'),
	(97, 'Maldive Rufiyaa', 'MVR'),
	(98, 'Malawi Kwacha', 'MWK'),
	(99, 'Mexican Peso', 'MXN'),
	(100, 'Malaysian Ringgit', 'MYR'),
	(101, 'Mozambique Metical', 'MZM'),
	(102, 'Nigerian Naira', 'NGN'),
	(103, 'Nicaraguan Cordoba', 'NIC'),
	(105, 'Norwegian Kroner', 'NOK'),
	(106, 'Nepalese Rupee', 'NPR'),
	(107, 'New Zealand Dollar', 'NZD'),
	(108, 'Omani Rial', 'OMR'),
	(109, 'Panamanian Balboa', 'PAB'),
	(110, 'Peruvian Nuevo Sol', 'PEN'),
	(111, 'Papua New Guinea Kina', 'PGK'),
	(112, 'Philippine Peso', 'PHP'),
	(113, 'Pakistan Rupee', 'PKR'),
	(114, 'Polish Złoty', 'PLN'),
	(116, 'Paraguay Guarani', 'PYG'),
	(117, 'Qatari Rial', 'QAR'),
	(118, 'Romanian Leu', 'RON'),
	(119, 'Rwanda Franc', 'RWF'),
	(120, 'Saudi Arabian Riyal', 'SAR'),
	(121, 'Solomon Islands Dollar', 'SBD'),
	(122, 'Seychelles Rupee', 'SCR'),
	(123, 'Sudanese Pound', 'SDP'),
	(124, 'Swedish Krona', 'SEK'),
	(125, 'Singapore Dollar', 'SGD'),
	(126, 'St. Helena Pound', 'SHP'),
	(127, 'Sierra Leone Leone', 'SLL'),
	(128, 'Somali Schilling', 'SOS'),
	(129, 'Suriname Guilder', 'SRG'),
	(130, 'Sao Tome and Principe Dobra', 'STD'),
	(131, 'Russian Ruble', 'RUB'),
	(132, 'El Salvador Colon', 'SVC'),
	(133, 'Syrian Potmd', 'SYP'),
	(134, 'Swaziland Lilangeni', 'SZL'),
	(135, 'Thai Bath', 'THB'),
	(136, 'Tunisian Dinar', 'TND'),
	(137, 'Tongan Pa''anga', 'TOP'),
	(138, 'East Timor Escudo', 'TPE'),
	(139, 'Turkish Lira', 'TRY'),
	(140, 'Trinidad and Tobago Dollar', 'TTD'),
	(141, 'Taiwan Dollar', 'TWD'),
	(142, 'Tanzanian Schilling', 'TZS'),
	(143, 'Uganda Shilling', 'UGS'),
	(144, 'US Dollar', 'USD'),
	(145, 'Uruguayan Peso', 'UYP'),
	(146, 'Venezualan Bolivar', 'VEB'),
	(147, 'Vietnamese Dong', 'VND'),
	(148, 'Vanuatu Vatu', 'VUV'),
	(149, 'Samoan Tala', 'WST'),
	(150, 'Democratic Yemeni Dinar', 'YDD'),
	(151, 'Yemeni Rial', 'YER'),
	(152, 'New Yugoslavia Dinar', 'YUD'),
	(153, 'South African Rand', 'ZAR'),
	(154, 'Zambian Kwacha', 'ZMK'),
	(155, 'Zaire Zaire', 'ZRZ'),
	(156, 'Zimbabwe Dollar', 'ZWD'),
	(157, 'Slovak Koruna', 'SKK'),
	(158, 'Armenian Dram', 'AMD');

INSERT IGNORE INTO `#__redshop_fields` (`id`, `title`, `name`, `type`, `desc`, `class`, `section`, `maxlength`, `cols`, `rows`, `size`, `show_in_front`, `required`, `published`, `publish_up`, `publish_down`, `display_in_product`, `ordering`, `display_in_checkout`, `checked_out`, `checked_out_time`, `created_date`, `created_by`, `modified_date`, `modified_by`)
VALUES
	(2, 'PNO', 'rs_pno', '1', '', '', '18', 30, 10, 10, 20, 1, 1, 1, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0, 2, 0, 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', NULL, '0000-00-00 00:00:00', NULL),
	(3, 'Birthdate', 'rs_birthdate', '12', '', '', '18', 30, 10, 10, 20, 1, 1, 1, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0, 3, 0, 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', NULL, '0000-00-00 00:00:00', NULL),
	(4, 'Gender', 'rs_gender', '4', '', '', '18', 30, 10, 10, 20, 1, 1, 1, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0, 4, 0, NULL, '0000-00-00 00:00:00', '0000-00-00 00:00:00', NULL, '0000-00-00 00:00:00', NULL),
	(5, 'House Number', 'rs_house_number', '1', '', '', '18', 30, 10, 10, 20, 1, 1, 1, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0, 5, 0, NULL, '0000-00-00 00:00:00', '0000-00-00 00:00:00', NULL, '0000-00-00 00:00:00', NULL),
	(6, 'House Extension', 'rs_house_extension', '1', '', '', '18', 30, 10, 10, 20, 1, 1, 1, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0, 6, 0, NULL, '0000-00-00 00:00:00', '0000-00-00 00:00:00', NULL, '0000-00-00 00:00:00', NULL);

INSERT IGNORE INTO `#__redshop_order_status` (`order_status_id`, `order_status_code`, `order_status_name`, `published`)
VALUES
	(1, 'P', 'Pending', 1),
	(2, 'C', 'Confirmed', 1),
	(3, 'X', 'Cancelled', 1),
	(4, 'R', 'Refunded', 1),
	(5, 'S', 'Shipped', 1),
	(6, 'RD', 'Ready for delivery', 1),
	(7, 'RD1', 'Ready for 1st delivery', 1),
	(8, 'RD2', 'Ready for 2nd delivery', 1),
	(9, 'ACCP', 'Awaiting credit card payment', 1),
	(10, 'APP', 'Awaiting paypal payment', 1),
	(11, 'ABT', 'Awaiting bank transfer', 1),
	(12, 'PR', 'Payment received', 1),
	(13, 'RC', 'Reclamation', 1),
	(14, 'PS', 'Partially shipped', 1),
	(15, 'RT', 'Returned', 1),
	(16, 'PRT', 'Partially Returned', 1),
	(17, 'PRC', 'Partially Reclamation', 1);

INSERT IGNORE INTO `#__redshop_state` (`id`, `country_id`, `state_name`, `state_3_code`, `state_2_code`) VALUES
	(1, 223, 'Alabama', 'ALA', 'AL'),
	(2, 223, 'Alaska', 'ALK', 'AK'),
	(3, 223, 'Arizona', 'ARZ', 'AZ'),
	(4, 223, 'Arkansas', 'ARK', 'AR'),
	(5, 223, 'California', 'CAL', 'CA'),
	(6, 223, 'Colorado', 'COL', 'CO'),
	(7, 223, 'Connecticut', 'CCT', 'CT'),
	(8, 223, 'Delaware', 'DEL', 'DE'),
	(9, 223, 'District Of Columbia', 'DOC', 'DC'),
	(10, 223, 'Florida', 'FLO', 'FL'),
	(11, 223, 'Georgia', 'GEA', 'GA'),
	(12, 223, 'Hawaii', 'HWI', 'HI'),
	(13, 223, 'Idaho', 'IDA', 'ID'),
	(14, 223, 'Illinois', 'ILL', 'IL'),
	(15, 223, 'Indiana', 'IND', 'IN'),
	(16, 223, 'Iowa', 'IOA', 'IA'),
	(17, 223, 'Kansas', 'KAS', 'KS'),
	(18, 223, 'Kentucky', 'KTY', 'KY'),
	(19, 223, 'Louisiana', 'LOA', 'LA'),
	(20, 223, 'Maine', 'MAI', 'ME'),
	(21, 223, 'Maryland', 'MLD', 'MD'),
	(22, 223, 'Massachusetts', 'MSA', 'MA'),
	(23, 223, 'Michigan', 'MIC', 'MI'),
	(24, 223, 'Minnesota', 'MIN', 'MN'),
	(25, 223, 'Mississippi', 'MIS', 'MS'),
	(26, 223, 'Missouri', 'MIO', 'MO'),
	(27, 223, 'Montana', 'MOT', 'MT'),
	(28, 223, 'Nebraska', 'NEB', 'NE'),
	(29, 223, 'Nevada', 'NEV', 'NV'),
	(30, 223, 'New Hampshire', 'NEH', 'NH'),
	(31, 223, 'New Jersey', 'NEJ', 'NJ'),
	(32, 223, 'New Mexico', 'NEM', 'NM'),
	(33, 223, 'New York', 'NEY', 'NY'),
	(34, 223, 'North Carolina', 'NOC', 'NC'),
	(35, 223, 'North Dakota', 'NOD', 'ND'),
	(36, 223, 'Ohio', 'OHI', 'OH'),
	(37, 223, 'Oklahoma', 'OKL', 'OK'),
	(38, 223, 'Oregon', 'ORN', 'OR'),
	(39, 223, 'Pennsylvania', 'PEA', 'PA'),
	(40, 223, 'Rhode Island', 'RHI', 'RI'),
	(41, 223, 'South Carolina', 'SOC', 'SC'),
	(42, 223, 'South Dakota', 'SOD', 'SD'),
	(43, 223, 'Tennessee', 'TEN', 'TN'),
	(44, 223, 'Texas', 'TXS', 'TX'),
	(45, 223, 'Utah', 'UTA', 'UT'),
	(46, 223, 'Vermont', 'VMT', 'VT'),
	(47, 223, 'Virginia', 'VIA', 'VA'),
	(48, 223, 'Washington', 'WAS', 'WA'),
	(49, 223, 'West Virginia', 'WEV', 'WV'),
	(50, 223, 'Wisconsin', 'WIS', 'WI'),
	(51, 223, 'Wyoming', 'WYO', 'WY'),
	(52, 38, 'Alberta', 'ALB', 'AB'),
	(53, 38, 'British Columbia', 'BRC', 'BC'),
	(54, 38, 'Manitoba', 'MAB', 'MB'),
	(55, 38, 'New Brunswick', 'NEB', 'NB'),
	(56, 38, 'Newfoundland and Labrador', 'NFL', 'NL'),
	(57, 38, 'Northwest Territories', 'NWT', 'NT'),
	(58, 38, 'Nova Scotia', 'NOS', 'NS'),
	(59, 38, 'Nunavut', 'NUT', 'NU'),
	(60, 38, 'Ontario', 'ONT', 'ON'),
	(61, 38, 'Prince Edward Island', 'PEI', 'PE'),
	(62, 38, 'Quebec', 'QEC', 'QC'),
	(63, 38, 'Saskatchewan', 'SAK', 'SK'),
	(64, 38, 'Yukon', 'YUT', 'YT'),
	(65, 222, 'England', 'ENG', 'EN'),
	(66, 222, 'Northern Ireland', 'NOI', 'NI'),
	(67, 222, 'Scotland', 'SCO', 'SD'),
	(68, 222, 'Wales', 'WLS', 'WS'),
	(69, 13, 'Australian Capital Territory', 'ACT', 'AT'),
	(70, 13, 'New South Wales', 'NSW', 'NW'),
	(71, 13, 'Northern Territory', 'NOT', 'NT'),
	(72, 13, 'Queensland', 'QLD', 'QL'),
	(73, 13, 'South Australia', 'SOA', 'SA'),
	(74, 13, 'Tasmania', 'TAS', 'TA'),
	(75, 13, 'Victoria', 'VIC', 'VI'),
	(76, 13, 'Western Australia', 'WEA', 'WA'),
	(77, 138, 'Aguascalientes', 'AGS', 'AG'),
	(78, 138, 'Baja California Norte', 'BCN', 'BN'),
	(79, 138, 'Baja California Sur', 'BCS', 'BS'),
	(80, 138, 'Campeche', 'CAM', 'CA'),
	(81, 138, 'Chiapas', 'CHI', 'CS'),
	(82, 138, 'Chihuahua', 'CHA', 'CH'),
	(83, 138, 'Coahuila', 'COA', 'CO'),
	(84, 138, 'Colima', 'COL', 'CM'),
	(85, 138, 'Distrito Federal', 'DFM', 'DF'),
	(86, 138, 'Durango', 'DGO', 'DO'),
	(87, 138, 'Guanajuato', 'GTO', 'GO'),
	(88, 138, 'Guerrero', 'GRO', 'GU'),
	(89, 138, 'Hidalgo', 'HGO', 'HI'),
	(90, 138, 'Jalisco', 'JAL', 'JA'),
	(91, 138, 'México (Estado de)', 'EDM', 'EM'),
	(92, 138, 'Michoacán', 'MCN', 'MI'),
	(93, 138, 'Morelos', 'MOR', 'MO'),
	(94, 138, 'Nayarit', 'NAY', 'NY'),
	(95, 138, 'Nuevo León', 'NUL', 'NL'),
	(96, 138, 'Oaxaca', 'OAX', 'OA'),
	(97, 138, 'Puebla', 'PUE', 'PU'),
	(98, 138, 'Querétaro', 'QRO', 'QU'),
	(99, 138, 'Quintana Roo', 'QUR', 'QR'),
	(100, 138, 'San Luis Potosí', 'SLP', 'SP'),
	(101, 138, 'Sinaloa', 'SIN', 'SI'),
	(102, 138, 'Sonora', 'SON', 'SO'),
	(103, 138, 'Tabasco', 'TAB', 'TA'),
	(104, 138, 'Tamaulipas', 'TAM', 'TM'),
	(105, 138, 'Tlaxcala', 'TLX', 'TX'),
	(106, 138, 'Veracruz', 'VER', 'VZ'),
	(107, 138, 'Yucatán', 'YUC', 'YU'),
	(108, 138, 'Zacatecas', 'ZAC', 'ZA'),
	(109, 30, 'Acre', 'ACR', 'AC'),
	(110, 30, 'Alagoas', 'ALG', 'AL'),
	(111, 30, 'Amapá', 'AMP', 'AP'),
	(112, 30, 'Amazonas', 'AMZ', 'AM'),
	(113, 30, 'Bahía', 'BAH', 'BA'),
	(114, 30, 'Ceará', 'CEA', 'CE'),
	(115, 30, 'Distrito Federal', 'DFB', 'DF'),
	(116, 30, 'Espirito Santo', 'ESS', 'ES'),
	(117, 30, 'Goiás', 'GOI', 'GO'),
	(118, 30, 'Maranhão', 'MAR', 'MA'),
	(119, 30, 'Mato Grosso', 'MAT', 'MT'),
	(120, 30, 'Mato Grosso do Sul', 'MGS', 'MS'),
	(121, 30, 'Minas Geraís', 'MIG', 'MG'),
	(122, 30, 'Paraná', 'PAR', 'PR'),
	(123, 30, 'Paraíba', 'PRB', 'PB'),
	(124, 30, 'Pará', 'PAB', 'PA'),
	(125, 30, 'Pernambuco', 'PER', 'PE'),
	(126, 30, 'Piauí', 'PIA', 'PI'),
	(127, 30, 'Rio Grande do Norte', 'RGN', 'RN'),
	(128, 30, 'Rio Grande do Sul', 'RGS', 'RS'),
	(129, 30, 'Rio de Janeiro', 'RDJ', 'RJ'),
	(130, 30, 'Rondônia', 'RON', 'RO'),
	(131, 30, 'Roraima', 'ROR', 'RR'),
	(132, 30, 'Santa Catarina', 'SAC', 'SC'),
	(133, 30, 'Sergipe', 'SER', 'SE'),
	(134, 30, 'São Paulo', 'SAP', 'SP'),
	(135, 30, 'Tocantins', 'TOC', 'TO'),
	(136, 44, 'Anhui', 'ANH', '34'),
	(137, 44, 'Beijing', 'BEI', '11'),
	(138, 44, 'Chongqing', 'CHO', '50'),
	(139, 44, 'Fujian', 'FUJ', '35'),
	(140, 44, 'Gansu', 'GAN', '62'),
	(141, 44, 'Guangdong', 'GUA', '44'),
	(142, 44, 'Guangxi Zhuang', 'GUZ', '45'),
	(143, 44, 'Guizhou', 'GUI', '52'),
	(144, 44, 'Hainan', 'HAI', '46'),
	(145, 44, 'Hebei', 'HEB', '13'),
	(146, 44, 'Heilongjiang', 'HEI', '23'),
	(147, 44, 'Henan', 'HEN', '41'),
	(148, 44, 'Hubei', 'HUB', '42'),
	(149, 44, 'Hunan', 'HUN', '43'),
	(150, 44, 'Jiangsu', 'JIA', '32'),
	(151, 44, 'Jiangxi', 'JIX', '36'),
	(152, 44, 'Jilin', 'JIL', '22'),
	(153, 44, 'Liaoning', 'LIA', '21'),
	(154, 44, 'Nei Mongol', 'NML', '15'),
	(155, 44, 'Ningxia Hui', 'NIH', '64'),
	(156, 44, 'Qinghai', 'QIN', '63'),
	(157, 44, 'Shandong', 'SNG', '37'),
	(158, 44, 'Shanghai', 'SHH', '31'),
	(159, 44, 'Shaanxi', 'SHX', '61'),
	(160, 44, 'Sichuan', 'SIC', '51'),
	(161, 44, 'Tianjin', 'TIA', '12'),
	(162, 44, 'Xinjiang Uygur', 'XIU', '65'),
	(163, 44, 'Xizang', 'XIZ', '54'),
	(164, 44, 'Yunnan', 'YUN', '53'),
	(165, 44, 'Zhejiang', 'ZHE', '33'),
	(166, 104, 'Gaza Strip', 'GZS', 'GZ'),
	(167, 104, 'West Bank', 'WBK', 'WB'),
	(168, 104, 'Other', 'OTH', 'OT'),
	(169, 151, 'St. Maarten', 'STM', 'SM'),
	(170, 151, 'Bonaire', 'BNR', 'BN'),
	(171, 151, 'Curacao', 'CUR', 'CR'),
	(172, 175, 'Alba', 'ABA', 'AB'),
	(173, 175, 'Arad', 'ARD', 'AR'),
	(174, 175, 'Arges', 'ARG', 'AG'),
	(175, 175, 'Bacau', 'BAC', 'BC'),
	(176, 175, 'Bihor', 'BIH', 'BH'),
	(177, 175, 'Bistrita-Nasaud', 'BIS', 'BN'),
	(178, 175, 'Botosani', 'BOT', 'BT'),
	(179, 175, 'Braila', 'BRL', 'BR'),
	(180, 175, 'Brasov', 'BRA', 'BV'),
	(181, 175, 'Bucuresti', 'BUC', 'B'),
	(182, 175, 'Buzau', 'BUZ', 'BZ'),
	(183, 175, 'Calarasi', 'CAL', 'CL'),
	(184, 175, 'Caras Severin', 'CRS', 'CS'),
	(185, 175, 'Cluj', 'CLJ', 'CJ'),
	(186, 175, 'Constanta', 'CST', 'CT'),
	(187, 175, 'Covasna', 'COV', 'CV'),
	(188, 175, 'Dambovita', 'DAM', 'DB'),
	(189, 175, 'Dolj', 'DLJ', 'DJ'),
	(190, 175, 'Galati', 'GAL', 'GL'),
	(191, 175, 'Giurgiu', 'GIU', 'GR'),
	(192, 175, 'Gorj', 'GOR', 'GJ'),
	(193, 175, 'Hargita', 'HRG', 'HR'),
	(194, 175, 'Hunedoara', 'HUN', 'HD'),
	(195, 175, 'Ialomita', 'IAL', 'IL'),
	(196, 175, 'Iasi', 'IAS', 'IS'),
	(197, 175, 'Ilfov', 'ILF', 'IF'),
	(198, 175, 'Maramures', 'MAR', 'MM'),
	(199, 175, 'Mehedinti', 'MEH', 'MH'),
	(200, 175, 'Mures', 'MUR', 'MS'),
	(201, 175, 'Neamt', 'NEM', 'NT'),
	(202, 175, 'Olt', 'OLT', 'OT'),
	(203, 175, 'Prahova', 'PRA', 'PH'),
	(204, 175, 'Salaj', 'SAL', 'SJ'),
	(205, 175, 'Satu Mare', 'SAT', 'SM'),
	(206, 175, 'Sibiu', 'SIB', 'SB'),
	(207, 175, 'Suceava', 'SUC', 'SV'),
	(208, 175, 'Teleorman', 'TEL', 'TR'),
	(209, 175, 'Timis', 'TIM', 'TM'),
	(210, 175, 'Tulcea', 'TUL', 'TL'),
	(211, 175, 'Valcea', 'VAL', 'VL'),
	(212, 175, 'Vaslui', 'VAS', 'VS'),
	(213, 175, 'Vrancea', 'VRA', 'VN'),
	(214, 105, 'Agrigento', 'AGR', 'AG'),
	(215, 105, 'Alessandria', 'ALE', 'AL'),
	(216, 105, 'Ancona', 'ANC', 'AN'),
	(217, 105, 'Aosta', 'AOS', 'AO'),
	(218, 105, 'Arezzo', 'ARE', 'AR'),
	(219, 105, 'Ascoli Piceno', 'API', 'AP'),
	(220, 105, 'Asti', 'AST', 'AT'),
	(221, 105, 'Avellino', 'AVE', 'AV'),
	(222, 105, 'Bari', 'BAR', 'BA'),
	(223, 105, 'Belluno', 'BEL', 'BL'),
	(224, 105, 'Benevento', 'BEN', 'BN'),
	(225, 105, 'Bergamo', 'BEG', 'BG'),
	(226, 105, 'Biella', 'BIE', 'BI'),
	(227, 105, 'Bologna', 'BOL', 'BO'),
	(228, 105, 'Bolzano', 'BOZ', 'BZ'),
	(229, 105, 'Brescia', 'BRE', 'BS'),
	(230, 105, 'Brindisi', 'BRI', 'BR'),
	(231, 105, 'Cagliari', 'CAG', 'CA'),
	(232, 105, 'Caltanissetta', 'CAL', 'CL'),
	(233, 105, 'Campobasso', 'CBO', 'CB'),
	(234, 105, 'Carbonia-Iglesias', 'CAR', 'CI'),
	(235, 105, 'Caserta', 'CAS', 'CE'),
	(236, 105, 'Catania', 'CAT', 'CT'),
	(237, 105, 'Catanzaro', 'CTZ', 'CZ'),
	(238, 105, 'Chieti', 'CHI', 'CH'),
	(239, 105, 'Como', 'COM', 'CO'),
	(240, 105, 'Cosenza', 'COS', 'CS'),
	(241, 105, 'Cremona', 'CRE', 'CR'),
	(242, 105, 'Crotone', 'CRO', 'KR'),
	(243, 105, 'Cuneo', 'CUN', 'CN'),
	(244, 105, 'Enna', 'ENN', 'EN'),
	(245, 105, 'Ferrara', 'FER', 'FE'),
	(246, 105, 'Firenze', 'FIR', 'FI'),
	(247, 105, 'Foggia', 'FOG', 'FG'),
	(248, 105, 'Forli-Cesena', 'FOC', 'FC'),
	(249, 105, 'Frosinone', 'FRO', 'FR'),
	(250, 105, 'Genova', 'GEN', 'GE'),
	(251, 105, 'Gorizia', 'GOR', 'GO'),
	(252, 105, 'Grosseto', 'GRO', 'GR'),
	(253, 105, 'Imperia', 'IMP', 'IM'),
	(254, 105, 'Isernia', 'ISE', 'IS'),
	(255, 105, 'L''Aquila', 'AQU', 'AQ'),
	(256, 105, 'La Spezia', 'LAS', 'SP'),
	(257, 105, 'Latina', 'LAT', 'LT'),
	(258, 105, 'Lecce', 'LEC', 'LE'),
	(259, 105, 'Lecco', 'LCC', 'LC'),
	(260, 105, 'Livorno', 'LIV', 'LI'),
	(261, 105, 'Lodi', 'LOD', 'LO'),
	(262, 105, 'Lucca', 'LUC', 'LU'),
	(263, 105, 'Macerata', 'MAC', 'MC'),
	(264, 105, 'Mantova', 'MAN', 'MN'),
	(265, 105, 'Massa-Carrara', 'MAS', 'MS'),
	(266, 105, 'Matera', 'MAA', 'MT'),
	(267, 105, 'Medio Campidano', 'MED', 'VS'),
	(268, 105, 'Messina', 'MES', 'ME'),
	(269, 105, 'Milano', 'MIL', 'MI'),
	(270, 105, 'Modena', 'MOD', 'MO'),
	(271, 105, 'Napoli', 'NAP', 'NA'),
	(272, 105, 'Novara', 'NOV', 'NO'),
	(273, 105, 'Nuoro', 'NUR', 'NU'),
	(274, 105, 'Ogliastra', 'OGL', 'OG'),
	(275, 105, 'Olbia-Tempio', 'OLB', 'OT'),
	(276, 105, 'Oristano', 'ORI', 'OR'),
	(277, 105, 'Padova', 'PDA', 'PD'),
	(278, 105, 'Palermo', 'PAL', 'PA'),
	(279, 105, 'Parma', 'PAA', 'PR'),
	(280, 105, 'Pavia', 'PAV', 'PV'),
	(281, 105, 'Perugia', 'PER', 'PG'),
	(282, 105, 'Pesaro e Urbino', 'PES', 'PU'),
	(283, 105, 'Pescara', 'PSC', 'PE'),
	(284, 105, 'Piacenza', 'PIA', 'PC'),
	(285, 105, 'Pisa', 'PIS', 'PI'),
	(286, 105, 'Pistoia', 'PIT', 'PT'),
	(287, 105, 'Pordenone', 'POR', 'PN'),
	(288, 105, 'Potenza', 'PTZ', 'PZ'),
	(289, 105, 'Prato', 'PRA', 'PO'),
	(290, 105, 'Ragusa', 'RAG', 'RG'),
	(291, 105, 'Ravenna', 'RAV', 'RA'),
	(292, 105, 'Reggio Calabria', 'REG', 'RC'),
	(293, 105, 'Reggio Emilia', 'REE', 'RE'),
	(294, 105, 'Rieti', 'RIE', 'RI'),
	(295, 105, 'Rimini', 'RIM', 'RN'),
	(296, 105, 'Roma', 'ROM', 'RM'),
	(297, 105, 'Rovigo', 'ROV', 'RO'),
	(298, 105, 'Salerno', 'SAL', 'SA'),
	(299, 105, 'Sassari', 'SAS', 'SS'),
	(300, 105, 'Savona', 'SAV', 'SV'),
	(301, 105, 'Siena', 'SIE', 'SI'),
	(302, 105, 'Siracusa', 'SIR', 'SR'),
	(303, 105, 'Sondrio', 'SOO', 'SO'),
	(304, 105, 'Taranto', 'TAR', 'TA'),
	(305, 105, 'Teramo', 'TER', 'TE'),
	(306, 105, 'Terni', 'TRN', 'TR'),
	(307, 105, 'Torino', 'TOR', 'TO'),
	(308, 105, 'Trapani', 'TRA', 'TP'),
	(309, 105, 'Trento', 'TRE', 'TN'),
	(310, 105, 'Treviso', 'TRV', 'TV'),
	(311, 105, 'Trieste', 'TRI', 'TS'),
	(312, 105, 'Udine', 'UDI', 'UD'),
	(313, 105, 'Varese', 'VAR', 'VA'),
	(314, 105, 'Venezia', 'VEN', 'VE'),
	(315, 105, 'Verbano Cusio Ossola', 'VCO', 'VB'),
	(316, 105, 'Vercelli', 'VER', 'VC'),
	(317, 105, 'Verona', 'VRN', 'VR'),
	(318, 105, 'Vibo Valenzia', 'VIV', 'VV'),
	(319, 105, 'Vicenza', 'VII', 'VI'),
	(320, 105, 'Viterbo', 'VIT', 'VT'),
	(321, 195, 'A Coruña', 'ACO', '15'),
	(322, 195, 'Alava', 'ALA', '01'),
	(323, 195, 'Albacete', 'ALB', '02'),
	(324, 195, 'Alicante', 'ALI', '03'),
	(325, 195, 'Almeria', 'ALM', '04'),
	(326, 195, 'Asturias', 'AST', '33'),
	(327, 195, 'Avila', 'AVI', '05'),
	(328, 195, 'Badajoz', 'BAD', '06'),
	(329, 195, 'Baleares', 'BAL', '07'),
	(330, 195, 'Barcelona', 'BAR', '08'),
	(331, 195, 'Burgos', 'BUR', '09'),
	(332, 195, 'Caceres', 'CAC', '10'),
	(333, 195, 'Cadiz', 'CAD', '11'),
	(334, 195, 'Cantabria', 'CAN', '39'),
	(335, 195, 'Castellon', 'CAS', '12'),
	(336, 195, 'Ceuta', 'CEU', '51'),
	(337, 195, 'Ciudad Real', 'CIU', '13'),
	(338, 195, 'Cordoba', 'COR', '14'),
	(339, 195, 'Cuenca', 'CUE', '16'),
	(340, 195, 'Girona', 'GIR', '17'),
	(341, 195, 'Granada', 'GRA', '18'),
	(342, 195, 'Guadalajara', 'GUA', '19'),
	(343, 195, 'Guipuzcoa', 'GUI', '20'),
	(344, 195, 'Huelva', 'HUL', '21'),
	(345, 195, 'Huesca', 'HUS', '22'),
	(346, 195, 'Jaen', 'JAE', '23'),
	(347, 195, 'La Rioja', 'LRI', '26'),
	(348, 195, 'Las Palmas', 'LPA', '35'),
	(349, 195, 'Leon', 'LEO', '24'),
	(350, 195, 'Lleida', 'LLE', '25'),
	(351, 195, 'Lugo', 'LUG', '27'),
	(352, 195, 'Madrid', 'MAD', '28'),
	(353, 195, 'Malaga', 'MAL', '29'),
	(354, 195, 'Melilla', 'MEL', '52'),
	(355, 195, 'Murcia', 'MUR', '30'),
	(356, 195, 'Navarra', 'NAV', '31'),
	(357, 195, 'Ourense', 'OUR', '32'),
	(358, 195, 'Palencia', 'PAL', '34'),
	(359, 195, 'Pontevedra', 'PON', '36'),
	(360, 195, 'Salamanca', 'SAL', '37'),
	(361, 195, 'Santa Cruz de Tenerife', 'SCT', '38'),
	(362, 195, 'Segovia', 'SEG', '40'),
	(363, 195, 'Sevilla', 'SEV', '41'),
	(364, 195, 'Soria', 'SOR', '42'),
	(365, 195, 'Tarragona', 'TAR', '43'),
	(366, 195, 'Teruel', 'TER', '44'),
	(367, 195, 'Toledo', 'TOL', '45'),
	(368, 195, 'Valencia', 'VAL', '46'),
	(369, 195, 'Valladolid', 'VLL', '47'),
	(370, 195, 'Vizcaya', 'VIZ', '48'),
	(371, 195, 'Zamora', 'ZAM', '49'),
	(372, 195, 'Zaragoza', 'ZAR', '50'),
	(373, 11, 'Aragatsotn', 'ARG', 'AG'),
	(374, 11, 'Ararat', 'ARR', 'AR'),
	(375, 11, 'Armavir', 'ARM', 'AV'),
	(376, 11, 'Gegharkunik', 'GEG', 'GR'),
	(377, 11, 'Kotayk', 'KOT', 'KT'),
	(378, 11, 'Lori', 'LOR', 'LO'),
	(379, 11, 'Shirak', 'SHI', 'SH'),
	(380, 11, 'Syunik', 'SYU', 'SU'),
	(381, 11, 'Tavush', 'TAV', 'TV'),
	(382, 11, 'Vayots-Dzor', 'VAD', 'VD'),
	(383, 11, 'Yerevan', 'YER', 'ER'),
	(384, 99, 'Andaman & Nicobar Islands', 'ANI', 'AI'),
	(385, 99, 'Andhra Pradesh', 'AND', 'AN'),
	(386, 99, 'Arunachal Pradesh', 'ARU', 'AR'),
	(387, 99, 'Assam', 'ASS', 'AS'),
	(388, 99, 'Bihar', 'BIH', 'BI'),
	(389, 99, 'Chandigarh', 'CHA', 'CA'),
	(390, 99, 'Chhatisgarh', 'CHH', 'CH'),
	(391, 99, 'Dadra & Nagar Haveli', 'DAD', 'DD'),
	(392, 99, 'Daman & Diu', 'DAM', 'DA'),
	(393, 99, 'Delhi', 'DEL', 'DE'),
	(394, 99, 'Goa', 'GOA', 'GO'),
	(395, 99, 'Gujarat', 'GUJ', 'GU'),
	(396, 99, 'Haryana', 'HAR', 'HA'),
	(397, 99, 'Himachal Pradesh', 'HIM', 'HI'),
	(398, 99, 'Jammu & Kashmir', 'JAM', 'JA'),
	(399, 99, 'Jharkhand', 'JHA', 'JH'),
	(400, 99, 'Karnataka', 'KAR', 'KA'),
	(401, 99, 'Kerala', 'KER', 'KE'),
	(402, 99, 'Lakshadweep', 'LAK', 'LA'),
	(403, 99, 'Madhya Pradesh', 'MAD', 'MD'),
	(404, 99, 'Maharashtra', 'MAH', 'MH'),
	(405, 99, 'Manipur', 'MAN', 'MN'),
	(406, 99, 'Meghalaya', 'MEG', 'ME'),
	(407, 99, 'Mizoram', 'MIZ', 'MI'),
	(408, 99, 'Nagaland', 'NAG', 'NA'),
	(409, 99, 'Orissa', 'ORI', 'OR'),
	(410, 99, 'Pondicherry', 'PON', 'PO'),
	(411, 99, 'Punjab', 'PUN', 'PU'),
	(412, 99, 'Rajasthan', 'RAJ', 'RA'),
	(413, 99, 'Sikkim', 'SIK', 'SI'),
	(414, 99, 'Tamil Nadu', 'TAM', 'TA'),
	(415, 99, 'Tripura', 'TRI', 'TR'),
	(416, 99, 'Uttaranchal', 'UAR', 'UA'),
	(417, 99, 'Uttar Pradesh', 'UTT', 'UT'),
	(418, 99, 'West Bengal', 'WES', 'WE'),
	(419, 101, 'Ahmadi va Kohkiluyeh', 'BOK', 'BO'),
	(420, 101, 'Ardabil', 'ARD', 'AR'),
	(421, 101, 'Azarbayjan-e Gharbi', 'AZG', 'AG'),
	(422, 101, 'Azarbayjan-e Sharqi', 'AZS', 'AS'),
	(423, 101, 'Bushehr', 'BUS', 'BU'),
	(424, 101, 'Chaharmahal va Bakhtiari', 'CMB', 'CM'),
	(425, 101, 'Esfahan', 'ESF', 'ES'),
	(426, 101, 'Fars', 'FAR', 'FA'),
	(427, 101, 'Gilan', 'GIL', 'GI'),
	(428, 101, 'Gorgan', 'GOR', 'GO'),
	(429, 101, 'Hamadan', 'HAM', 'HA'),
	(430, 101, 'Hormozgan', 'HOR', 'HO'),
	(431, 101, 'Ilam', 'ILA', 'IL'),
	(432, 101, 'Kerman', 'KER', 'KE'),
	(433, 101, 'Kermanshah', 'BAK', 'BA'),
	(434, 101, 'Khorasan-e Junoubi', 'KHJ', 'KJ'),
	(435, 101, 'Khorasan-e Razavi', 'KHR', 'KR'),
	(436, 101, 'Khorasan-e Shomali', 'KHS', 'KS'),
	(437, 101, 'Khuzestan', 'KHU', 'KH'),
	(438, 101, 'Kordestan', 'KOR', 'KO'),
	(439, 101, 'Lorestan', 'LOR', 'LO'),
	(440, 101, 'Markazi', 'MAR', 'MR'),
	(441, 101, 'Mazandaran', 'MAZ', 'MZ'),
	(442, 101, 'Qazvin', 'QAS', 'QA'),
	(443, 101, 'Qom', 'QOM', 'QO'),
	(444, 101, 'Semnan', 'SEM', 'SE'),
	(445, 101, 'Sistan va Baluchestan', 'SBA', 'SB'),
	(446, 101, 'Tehran', 'TEH', 'TE'),
	(447, 101, 'Yazd', 'YAZ', 'YA'),
	(448, 101, 'Zanjan', 'ZAN', 'ZA'),
	(449, 170, 'Dolnośląskie', 'DOL', 'DO'),
	(450, 170, 'Kujawsko-Pomorskie', 'KUJ', 'KU'),
	(451, 170, 'Lubelskie', 'LUB', 'LU'),
	(452, 170, 'Lubuskie', 'LBU', 'LB'),
	(453, 170, 'Łódzkie', 'LOD', 'LO'),
	(454, 170, 'Małopolskie', 'MAL', 'MP'),
	(455, 170, 'Mazowieckie', 'MAZ', 'MZ'),
	(456, 170, 'Opolskie', 'OPO', 'OP'),
	(457, 170, 'Podkarpackie', 'PDK', 'PK'),
	(458, 170, 'Podlaskie', 'PDL', 'PL'),
	(459, 170, 'Pomorskie', 'POM', 'PO'),
	(460, 170, 'Śląskie', 'SLA', 'SL'),
	(461, 170, 'Świętokrzyskie', 'SWI', 'SW'),
	(462, 170, 'Warmińsko-Mazurskie', 'WAR', 'WA'),
	(463, 170, 'Wielkopolskie', 'WIE', 'WI'),
	(464, 170, 'Zachodniopomorskie', 'ZAC', 'ZA');

INSERT IGNORE INTO `#__redshop_stockroom` (`stockroom_id`, `stockroom_name`, `stockroom_desc`, `published`) VALUES
	(1, 'default', 'This is redshop default stockroom', '1');

INSERT IGNORE INTO `#__redshop_mail` (`mail_id`, `mail_name`, `mail_subject`, `mail_section`, `mail_order_status`, `mail_body`, `published`, `mail_bcc`) VALUES
	(1, 'Ask Question', 'Ask Question About Product', 'ask_question_mail', '0', '<p>To Admin,</p>\r\n<p>Product  : {product_name}</p>\r\n<p>Please check this link : {product_link}</p>\r\n<p> </p>\r\n<p>{user_question}</p>\r\n<p>{answer}</p>\r\n<p> </p>', 1, ''),
	(11, 'Send to friend', 'Send to friend', 'product', '0', '<p>Hi {friend_name} ,</p>\r\n<p>New Product  : {product_name}</p>\r\n<p>{product_desc} Please check this link : {product_url}</p>\r\n<p> </p>\r\n<p> </p>', 1, ''),
	(12, 'Tax exempt approval mail', 'Tax exempt approval mail subject', 'tax_exempt_approval_mail', '0', '<p>Hello,</p>\r\n<p>Tax exempt has been approved</p>', 1, ''),
	(13, 'Tax exempt disapproval mail', 'Tax exempt disapproval mail subject', 'tax_exempt_disapproval_mail', '0', '<p>Hello,</p>\r\n<p>Tax exempt  has been disapproved.</p>', 1, ''),
	(14, 'Tax exempt waiting approval mail', 'Tax exempt waiting approval mail subject', 'tax_exempt_waiting_approval_mail', '0', '<p>Tax exempt waiting approval mail contents...</p>\r\n<p>Thanks.</p>', 1, ''),
	(15, 'Registration mail', 'Registration mail', 'register', '0', '<table style="border: 1px solid #ccc; background: #fff; width: 600px;" cellpadding="0" cellspacing="0">\r\n<tbody>\r\n<tr>\r\n<td>\r\n<table border="0" cellpadding="0" cellspacing="0">\r\n<tbody>\r\n<tr>\r\n<td style="width: 20px;"></td>\r\n<td>\r\n<table style="width: 100%;">\r\n<tbody>\r\n<tr>\r\n<td width="400px"><a href="http://redcomponent.com" target="_blank"> <img src="http://redcomponent.com/images/redcomponent_logo.png" style="width: 340px; height: auto; padding-top: 20px;" /> </a></td>\r\n<td style="font-size: 12px; color: #878787; float: right;"></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n<td style="width: 20px;"></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<table style="width: 100%;" cellpadding="0" cellspacing="0">\r\n<tbody>\r\n<tr>\r\n<td style="height: 20px; background-color: #444544;"></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<table border="0" cellpadding="0" cellspacing="0">\r\n<tbody>\r\n<tr>\r\n<td colspan="3" style="height: 20px;"></td>\r\n</tr>\r\n<tr>\r\n<td style="width: 20px;"></td>\r\n<td>\r\n<p style="font-size: 24px; font-family: verdana; color: #616161; text-align: justify;">Thank you for your registration!</p>\r\n<p style="font-size: 14px; font-family: verdana; color: #616161; text-align: justify;">You are now a registered user at redCOMPONENT.</p>\r\n<p style="font-size: 14px; font-family: verdana; color: #616161; text-align: justify; line-height: 20px;">To go to your account where you can make all necessary adjustments, such as change your address book, view old orders, download your purchased products, or sign up for our newsletter please click {account_link}.</p>\r\n<p style="font-size: 14px; font-family: verdana; color: #616161; text-align: justify;">�</p>\r\n<p style="font-size: 14px; font-family: verdana; color: #616161; text-align: justify;"><strong>User information:</strong></p>\r\n<p style="font-size: 14px; font-family: verdana; color: #616161; text-align: justify;">Username: {username}</p>\r\n<p style="font-size: 14px; font-family: verdana; color: #616161; text-align: justify;">Password: {password}</p>\r\n<p style="font-size: 14px; font-family: verdana; color: #616161; text-align: justify;">�</p>\r\n<p style="font-size: 14px; font-family: verdana; color: #616161; text-align: justify;">Regards,<br />{shopname}</p>\r\n</td>\r\n<td style="width: 20px;"></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<table style="margin-top: 30px; width: 100%;" cellpadding="0" cellspacing="0">\r\n<tbody>\r\n<tr>\r\n<td style="height: 45px; background-color: #444544; display: block !important;"></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>', 1, ''),
	(16, 'Catlog First Reminder', 'Catlog First Reminder', 'catalog_first_reminder', '0', '<!-- 		@page { margin: 0.79in } 		P { margin-bottom: 0.08in } 	-->\r\n<p style="margin-left: 0.5in; margin-bottom: 0in; text-align: left;"><strong><span style="font-family: Verdana,sans-serif;"><span style="font-size: x-small;">Dear {name}. <br /></span></span></strong></p>\r\n<p style="margin-left: 0.5in; margin-bottom: 0in; text-align: left;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: x-small;"><span> My name is xyz, in charge of customer support here at abc. We sent you our catalogue the other day, and I would just like to know if you had a chance to look at it...? In any case, I am ready by the phone / e-mail if you need any assistance whatsoever. </span></span></span></p>\r\n<p style="margin-left: 0.5in; margin-bottom: 0in; text-align: left;"><strong><span style="font-family: Verdana,sans-serif;"><span style="font-size: x-small;"><span>Kind regards,</span></span></span></strong></p>\r\n<p style="margin-left: 0.5in; margin-bottom: 0in; text-align: left;"><strong><span style="font-family: Verdana,sans-serif;"><span style="font-size: x-small;"><span>Name<br /></span></span></span></strong></p>\r\n<p style="margin-left: 0.5in; margin-bottom: 0in;"> </p>', 1, ''),
	(17, 'Catlog Second Reminder', 'Catlog Second Reminder', 'catalog_second_reminder', '0', '<p style="background: #ffffff none repeat scroll 0% 0%; margin-left: 0.5in; margin-bottom: 0in; -moz-background-clip: -moz-initial; -moz-background-origin: -moz-initial; -moz-background-inline-policy: -moz-initial; text-align: left;"><strong><span style="font-family: Verdana,sans-serif;"><span style="font-size: x-small;"><span>Dear {name}, </span></span></span></strong></p>\r\n<p style="background: #ffffff none repeat scroll 0% 0%; margin-left: 0.5in; margin-bottom: 0in; -moz-background-clip: -moz-initial; -moz-background-origin: -moz-initial; -moz-background-inline-policy: -moz-initial; text-align: left;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: x-small;"><span> I just wish to inform you that we are currently running a campaign for all the clients who received our catalogue earlier. This means that in the next 4 days, you get </span></span></span><span style="color: #ff0000;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: x-small;"><span>5% </span></span></span></span><span style="font-family: Verdana,sans-serif;"><span style="font-size: x-small;"><span>off everything you buy, and since our products are already competitively priced, it is a really good offer. You can use the code: XXX when you order to get the discount, but remember you have 4 days from now to decide!</span></span></span></p>\r\n<p style="background: #ffffff none repeat scroll 0% 0%; margin-left: 0.5in; margin-bottom: 0in; -moz-background-clip: -moz-initial; -moz-background-origin: -moz-initial; -moz-background-inline-policy: -moz-initial; text-align: left;"> </p>\r\n<p style="background: #ffffff none repeat scroll 0% 0%; margin-left: 0.5in; margin-bottom: 0in; -moz-background-clip: -moz-initial; -moz-background-origin: -moz-initial; -moz-background-inline-policy: -moz-initial; text-align: left;"><strong>Regards,</strong></p>\r\n<p style="background: #ffffff none repeat scroll 0% 0%; margin-left: 0.5in; margin-bottom: 0in; -moz-background-clip: -moz-initial; -moz-background-origin: -moz-initial; -moz-background-inline-policy: -moz-initial; text-align: left;"><strong>xyz. </strong></p>', 1, ''),
	(18, 'Catlog Sample First Reminder', 'Catlog Sample First Reminder', 'colour_sample_first_reminder', '0', '<!-- 		@page { margin: 0.79in } 		P { margin-bottom: 0.08in } 	-->\r\n<p style="margin-left: 0.5in; margin-bottom: 0in;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: x-small;"><span>Dear {name}. My name is xyz, in charge of customer support here at xyz. You have requested some colour samples, and I will send them to you as soon as possible. If you have any questions, please do not hesitate to contact me. </span></span></span><span style="font-family: Verdana,sans-serif;"><span style="font-size: x-small;">Kind regards, xyz</span></span></p>', 1, ''),
	(19, 'Catlog Sample Second Reminder', 'Catlog Sample Second Reminder', 'colour_sample_second_reminder', '0', '<!-- 		@page { margin: 0.79in } 		P { margin-bottom: 0.08in } 	-->\r\n<p style="margin-left: 0.5in; margin-bottom: 0in;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: x-small;"><span>Dear {name}. I sent you some sample colour material the other day, and I would just like to know if you had a chance to look at it...? In any case, I am ready by the phone / e-mail if you need any assistance whatsoever. Kind regards, xyz</span></span></span></p>', 1, ''),
	(20, 'Catlog Sample Third Reminder', 'Catlog Sample Third Reminder', 'colour_sample_third_reminder', '0', '<!-- 		@page { margin: 0.79in } 		P { margin-bottom: 0.08in } 	-->\r\n<p style="margin-left: 0.5in; margin-bottom: 0in;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: x-small;"><span>Dear {name}. I just wish to inform you that we are currently running a campaign for all the clients who received sample colour material from us earlier. This means that in the next 4 days, you get 5% off everything you buy, and since our products are already competitively priced, it is a really good offer. You can use the code: XXX when you order to get the discount, but remember you have 4 days from now to decide!</span></span></span></p>', 1, ''),
	(21, 'Order Mail', 'Order Mail for {order_id}', 'order', '0', '<table style="border: 1px solid #ccc; background: #fff; width: 700px;" cellspacing="0" cellpadding="0"><tbody><tr><td style="line-height: 25px;"><table style="width: 100%; background: #f7f7f7;" border="0" cellspacing="0" cellpadding="0"><tbody><tr><td style="height: 10px;" colspan="3"> </td></tr><tr><td style="width: 20px;"> </td><td style="line-height: 25px;"><table style="width: 100%;"><tbody><tr><td width="400px"><a href="http://redcomponent.com" target="_blank"> <img style="width: 340px; height: auto; padding-top: 20px;" src="http://redcomponent.com/images/redcomponent_logo.png" /> </a></td><td style="font-size: 12px; color: #878787; float: right; text-align: right; font-family: verdana; vertical-align: top;">{order_date}</td></tr></tbody></table></td><td style="width: 20px;"> </td></tr></tbody></table><table style="width: 100%;" cellspacing="0" cellpadding="0"><tbody><tr><td style="height: 20px; background-color: #444544;"> </td></tr></tbody></table><table style="width: 100%;" border="0" cellspacing="0" cellpadding="0"><tbody><tr><td style="height: 20px;" colspan="3"> </td></tr><tr><td style="width: 20px;"> </td><td style="line-height: 25px;"><p style="font-size: 24px; font-family: verdana; color: #666666; text-align: justify;"><strong>Thank you for your order!</strong></p><p style="font-size: 14px; font-family: verdana; color: #666666; text-align: justify;">Thank you for ordering from redCOMPONENT!</p><p style="font-size: 14px; font-family: verdana; color: #666666; text-align: justify; margin-bottom: 0 !important;"> </p><p style="font-size: 14px; font-family: verdana; color: #666666; text-align: justify; margin-bottom: 5px !important;"><strong>Products ordered:</strong></p><table style="width: 100%; line-height: 25px;" border="0" cellspacing="0" cellpadding="0"><tbody><!--{product_loop_start}--><tr style="border-bottom: 1px solid #F1F1F1;"><td colspan="3"><table style="width: 100%;" cellspacing="0" cellpadding="0"><tbody><tr><td style="width: 32px; vertical-align: top;"><span style="font-size: 14px; font-family: verdana; color: #666666; text-align: justify;"> {product_quantity} x </span></td><td><div><span style="font-size: 14px; font-family: verdana; color: #666666; text-align: justify;">{product_name}{without_vat}</span> <span style="font-size: 14px; font-family: verdana; color: #666666; text-align: justify;">{product_accessory}</span></div><span style="font-size: 13px; font-family: verdana; color: #666666;">{product_attribute}</span></td></tr></tbody></table></td><td style="vertical-align: top;" align="right"><span style="font-size: 14px; font-family: verdana; color: #666666; text-align: right;">{product_total_price}</span></td></tr><!--{product_loop_end}--> <!--{if discount}--><tr><td colspan="3"><span style="font-size: 14px; font-family: verdana; color: #666666; text-align: justify;">Discount</span></td><td align="right"><span style="font-size: 14px; font-family: verdana; color: #666666; text-align: justify;">{discount_excl_vat}</span></td></tr><!--{discount end if}--><tr><td style="padding-top: 10px;" colspan="3"><span style="font-size: 14px; font-family: verdana; color: #666666; text-align: justify;">VAT</span></td><td align="right"><span style="font-size: 14px; font-family: verdana; color: #666666; text-align: justify;">{sub_total_vat}</span></td></tr><tr><td colspan="3"><span style="font-size: 14px; font-family: verdana; color: #666666; text-align: justify;"><strong>Total</strong></span></td><td align="right"><span style="font-size: 14px; font-family: verdana; color: #666666; text-align: justify;"><strong>{order_total}</strong></span></td></tr></tbody></table><table style="width: 100%; line-height: 25px;" border="0" cellspacing="0" cellpadding="0"><tbody><tr><td style="vertical-align: top;"><p style="font-size: 14px; font-family: verdana; color: #666666; text-align: justify; margin-bottom: 5px !important;"><strong>Billing information: </strong></p><div style="font-size: 14px; font-family: verdana; color: #666666; text-align: justify;">{billing_address}</div></td><td style="vertical-align: top;"><p style="font-size: 14px; font-family: verdana; color: #666666; text-align: justify; margin-bottom: 5px !important;"><strong>Shipping information: </strong></p><div style="font-size: 14px; font-family: verdana; color: #666666; text-align: justify;">{shipping_address}</div></td></tr></tbody></table><p style="font-size: 14px; font-family: verdana; color: #666666; text-align: justify; margin-bottom: 5px !important;"><strong>Additional information:</strong></p><p style="font-size: 14px; font-family: verdana; color: #666666; text-align: justify; margin-bottom: 5px !important;">{customer_note}</p><p> </p><p style="font-size: 14px; font-family: verdana; color: #666666; text-align: justify; margin-bottom: 5px !important;"><strong>Order details:</strong></p><p style="font-size: 14px; font-family: verdana; color: #666666; text-align: justify;">To see the details of your order please {order_detail_link}.</p><p style="font-size: 14px; font-family: verdana; color: #666666; text-align: justify;"> </p><p style="font-size: 14px; font-family: verdana; color: #666666; text-align: justify;">Regards,<br />redCOMPONENT</p></td><td style="width: 20px; padding-bottom: 30px;"> </td></tr><tr style="height: 10px;"><td colspan="3"> </td></tr></tbody></table><table style="width: 100%;" cellspacing="0" cellpadding="0"><tbody><tr><td style="height: 45px; background-color: #444544; display: block !important;"> </td></tr></tbody></table></td></tr></tbody></table>', 1, ''),
	(22, 'Order Status Change Shipped', 'Order Status Change Shipped', 'order_status', 'S', '<table style="border: 1px solid #ccc;background: #fff; width:600px;" cellpadding="0" cellspacing="0">\r\n<tr>\r\n<td>\r\n\r\n<table border="0" cellpadding="0" cellspacing="0" style="width: 100%;background: #f7f7f7;">\r\n	<tbody>\r\n	<tr>\r\n		<td colspan="3" style="height: 20px;"></td>\r\n	</tr>\r\n	<tr>\r\n		<td style="width: 20px;"></td>\r\n		<td>\r\n<table width="100%" cellpadding="0" cellspacing="0">\r\n	<tr>\r\n		<td width="400px">\r\n			<a href="http://redcomponent.com" target="_blank"> <img src="http://redcomponent.com/images/redcomponent_logo.png" style="width: 340px; height: auto; padding-top: 20px;" /> </a>\r\n		</td>\r\n		<td style="font-size: 12px; color: #878787; float: right;text-align: right;font-family: verdana;vertical-align:top;">\r\n			{order_date}\r\n		</td>\r\n	</tr>\r\n</table>\r\n		</td>\r\n		<td style="width: 20px;"></td>\r\n	</tr>\r\n	</tbody>\r\n</table>\r\n\r\n<table width="100%" cellpadding="0" cellspacing="0">\r\n	<tr>\r\n		<td style="height: 20px; background-color: #444544;"></td>\r\n	</tr>\r\n</table>\r\n\r\n<table border="0" cellpadding="0" cellspacing="0" style="width: 100%">\r\n<tbody>\r\n	<tr>\r\n		<td colspan="3" style="height: 20px;"></td>\r\n	</tr>\r\n	<tr>\r\n		<td style="width: 20px;"></td>\r\n		<td>\r\n			<p style="font-size: 24px; font-family: verdana; color: #616161; text-align: justify;">Order status</p>\r\n			<p style="font-size: 14px; font-family: verdana; color: #616161; text-align: justify;">Your order status has changed.</p>\r\n			<p> </p>\r\n			<p> </p>\r\n			<p> </p>\r\n			<p style="font-size: 14px; font-family: verdana; color: #616161; text-align: justify;">Regards,<br />redCOMPONENT</p>\r\n		</td>\r\n		<td style="width: 20px;"></td>\r\n	</tr>\r\n<tr style="height: 160px">\r\n    <td colspan="3"></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n\r\n<table width="100%" style="margin-top: 30px;" cellpadding="0" cellspacing="0">\r\n	<tr>\r\n		<td style="height: 45px; background-color: #444544; display: block !important;"></td>\r\n	</tr>\r\n</table>\r\n</td>\r\n</tr>\r\n</table>', 1, ''),
	(23, 'Order Status Change Refunded', 'Order Status Change Refunded', 'order_status', 'R', '<table style="border: 1px solid #ccc;background: #fff; width:600px;" cellpadding="0" cellspacing="0">\r\n<tr>\r\n<td>\r\n\r\n<table border="0" cellpadding="0" cellspacing="0" style="width: 100%;background: #f7f7f7;">\r\n	<tbody>\r\n	<tr>\r\n		<td colspan="3" style="height: 20px;"></td>\r\n	</tr>\r\n	<tr>\r\n		<td style="width: 20px;"></td>\r\n		<td>\r\n<table width="100%" cellpadding="0" cellspacing="0">\r\n	<tr>\r\n		<td width="400px">\r\n			<a href="http://redcomponent.com" target="_blank"> <img src="http://redcomponent.com/images/redcomponent_logo.png" style="width: 340px; height: auto; padding-top: 20px;" /> </a>\r\n		</td>\r\n		<td style="font-size: 12px; color: #878787; float: right;text-align: right;font-family: verdana;vertical-align:top;">\r\n			{order_date}\r\n		</td>\r\n	</tr>\r\n</table>\r\n		</td>\r\n		<td style="width: 20px;"></td>\r\n	</tr>\r\n	</tbody>\r\n</table>\r\n\r\n<table width="100%" cellpadding="0" cellspacing="0">\r\n	<tr>\r\n		<td style="height: 20px; background-color: #444544;"></td>\r\n	</tr>\r\n</table>\r\n\r\n<table border="0" cellpadding="0" cellspacing="0" style="width: 100%">\r\n<tbody>\r\n	<tr>\r\n		<td colspan="3" style="height: 20px;"></td>\r\n	</tr>\r\n	<tr>\r\n		<td style="width: 20px;"></td>\r\n		<td>\r\n			<p style="font-size: 24px; font-family: verdana; color: #616161; text-align: justify;">Order status</p>\r\n			<p style="font-size: 14px; font-family: verdana; color: #616161; text-align: justify;">Your order status has changed.</p>\r\n			<p> </p>\r\n			<p> </p>\r\n			<p> </p>\r\n			<p style="font-size: 14px; font-family: verdana; color: #616161; text-align: justify;">Regards,<br />redCOMPONENT</p>\r\n		</td>\r\n		<td style="width: 20px;"></td>\r\n	</tr>\r\n<tr style="height: 160px">\r\n    <td colspan="3"></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n\r\n<table width="100%" style="margin-top: 30px;" cellpadding="0" cellspacing="0">\r\n	<tr>\r\n		<td style="height: 45px; background-color: #444544; display: block !important;"></td>\r\n	</tr>\r\n</table>\r\n</td>\r\n</tr>\r\n</table>', 1, ''),
	(24, 'Order Status Change Pending', 'Order Status Change Pending', 'order_status', 'P', '<table style="border: 1px solid #ccc;background: #fff; width:600px;" cellpadding="0" cellspacing="0">\r\n<tr>\r\n<td>\r\n\r\n<table border="0" cellpadding="0" cellspacing="0" style="width: 100%;background: #f7f7f7;">\r\n	<tbody>\r\n	<tr>\r\n		<td colspan="3" style="height: 20px;"></td>\r\n	</tr>\r\n	<tr>\r\n		<td style="width: 20px;"></td>\r\n		<td>\r\n<table width="100%" cellpadding="0" cellspacing="0">\r\n	<tr>\r\n		<td width="400px">\r\n			<a href="http://redcomponent.com" target="_blank"> <img src="http://redcomponent.com/images/redcomponent_logo.png" style="width: 340px; height: auto; padding-top: 20px;" /> </a>\r\n		</td>\r\n		<td style="font-size: 12px; color: #878787; float: right;text-align: right;font-family: verdana;vertical-align:top;">\r\n			{order_date}\r\n		</td>\r\n	</tr>\r\n</table>\r\n		</td>\r\n		<td style="width: 20px;"></td>\r\n	</tr>\r\n	</tbody>\r\n</table>\r\n\r\n<table width="100%" cellpadding="0" cellspacing="0">\r\n	<tr>\r\n		<td style="height: 20px; background-color: #444544;"></td>\r\n	</tr>\r\n</table>\r\n\r\n<table border="0" cellpadding="0" cellspacing="0" style="width: 100%">\r\n<tbody>\r\n	<tr>\r\n		<td colspan="3" style="height: 20px;"></td>\r\n	</tr>\r\n	<tr>\r\n		<td style="width: 20px;"></td>\r\n		<td>\r\n			<p style="font-size: 24px; font-family: verdana; color: #616161; text-align: justify;">Order status</p>\r\n			<p style="font-size: 14px; font-family: verdana; color: #616161; text-align: justify;">Your order status has changed.</p>\r\n			<p> </p>\r\n			<p> </p>\r\n			<p> </p>\r\n			<p style="font-size: 14px; font-family: verdana; color: #616161; text-align: justify;">Regards,<br />redCOMPONENT</p>\r\n		</td>\r\n		<td style="width: 20px;"></td>\r\n	</tr>\r\n<tr style="height: 160px">\r\n    <td colspan="3"></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n\r\n<table width="100%" style="margin-top: 30px;" cellpadding="0" cellspacing="0">\r\n	<tr>\r\n		<td style="height: 45px; background-color: #444544; display: block !important;"></td>\r\n	</tr>\r\n</table>\r\n</td>\r\n</tr>\r\n</table>', 1, ''),
	(25, 'Order Status Change Confirmed', 'Order Status Change Confirmed', 'order_status', 'C', '<table style="border: 1px solid #ccc;background: #fff; width:600px;" cellpadding="0" cellspacing="0">\r\n<tr>\r\n<td>\r\n\r\n<table border="0" cellpadding="0" cellspacing="0" style="width: 100%;background: #f7f7f7;">\r\n	<tbody>\r\n	<tr>\r\n		<td colspan="3" style="height: 20px;"></td>\r\n	</tr>\r\n	<tr>\r\n		<td style="width: 20px;"></td>\r\n		<td>\r\n<table width="100%" cellpadding="0" cellspacing="0">\r\n	<tr>\r\n		<td width="400px">\r\n			<a href="http://redcomponent.com" target="_blank"> <img src="http://redcomponent.com/images/redcomponent_logo.png" style="width: 340px; height: auto; padding-top: 20px;" /> </a>\r\n		</td>\r\n		<td style="font-size: 12px; color: #878787; float: right;text-align: right;font-family: verdana;vertical-align:top;">\r\n			{order_date}\r\n		</td>\r\n	</tr>\r\n</table>\r\n		</td>\r\n		<td style="width: 20px;"></td>\r\n	</tr>\r\n	</tbody>\r\n</table>\r\n\r\n<table width="100%" cellpadding="0" cellspacing="0">\r\n	<tr>\r\n		<td style="height: 20px; background-color: #444544;"></td>\r\n	</tr>\r\n</table>\r\n\r\n<table border="0" cellpadding="0" cellspacing="0" style="width: 100%">\r\n<tbody>\r\n	<tr>\r\n		<td colspan="3" style="height: 20px;"></td>\r\n	</tr>\r\n	<tr>\r\n		<td style="width: 20px;"></td>\r\n		<td>\r\n			<p style="font-size: 24px; font-family: verdana; color: #616161; text-align: justify;">Order status</p>\r\n			<p style="font-size: 14px; font-family: verdana; color: #616161; text-align: justify;">Your order status has changed.</p>\r\n			<p> </p>\r\n			<p> </p>\r\n			<p> </p>\r\n			<p style="font-size: 14px; font-family: verdana; color: #616161; text-align: justify;">Regards,<br />redCOMPONENT</p>\r\n		</td>\r\n		<td style="width: 20px;"></td>\r\n	</tr>\r\n<tr style="height: 160px">\r\n    <td colspan="3"></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n\r\n<table width="100%" style="margin-top: 30px;" cellpadding="0" cellspacing="0">\r\n	<tr>\r\n		<td style="height: 45px; background-color: #444544; display: block !important;"></td>\r\n	</tr>\r\n</table>\r\n</td>\r\n</tr>\r\n</table>', 1, ''),
	(26, 'Order Status Change Cancelled', 'Order Status Change Cancelled', 'order_status', 'X', '<table style="border: 1px solid #ccc;background: #fff; width:600px;" cellpadding="0" cellspacing="0">\r\n<tr>\r\n<td>\r\n\r\n<table border="0" cellpadding="0" cellspacing="0" style="width: 100%;background: #f7f7f7;">\r\n	<tbody>\r\n	<tr>\r\n		<td colspan="3" style="height: 20px;"></td>\r\n	</tr>\r\n	<tr>\r\n		<td style="width: 20px;"></td>\r\n		<td>\r\n<table width="100%" cellpadding="0" cellspacing="0">\r\n	<tr>\r\n		<td width="400px">\r\n			<a href="http://redcomponent.com" target="_blank"> <img src="http://redcomponent.com/images/redcomponent_logo.png" style="width: 340px; height: auto; padding-top: 20px;" /> </a>\r\n		</td>\r\n		<td style="font-size: 12px; color: #878787; float: right;text-align: right;font-family: verdana;vertical-align:top;">\r\n			{order_date}\r\n		</td>\r\n	</tr>\r\n</table>\r\n		</td>\r\n		<td style="width: 20px;"></td>\r\n	</tr>\r\n	</tbody>\r\n</table>\r\n\r\n<table width="100%" cellpadding="0" cellspacing="0">\r\n	<tr>\r\n		<td style="height: 20px; background-color: #444544;"></td>\r\n	</tr>\r\n</table>\r\n\r\n<table border="0" cellpadding="0" cellspacing="0" style="width: 100%">\r\n<tbody>\r\n	<tr>\r\n		<td colspan="3" style="height: 20px;"></td>\r\n	</tr>\r\n	<tr>\r\n		<td style="width: 20px;"></td>\r\n		<td>\r\n			<p style="font-size: 24px; font-family: verdana; color: #616161; text-align: justify;">Order status</p>\r\n			<p style="font-size: 14px; font-family: verdana; color: #616161; text-align: justify;">Your order status has changed.</p>\r\n			<p>�</p>\r\n			<p>�</p>\r\n			<p>�</p>\r\n			<p style="font-size: 14px; font-family: verdana; color: #616161; text-align: justify;">Regards,<br />redCOMPONENT</p>\r\n		</td>\r\n		<td style="width: 20px;"></td>\r\n	</tr>\r\n<tr style="height: 160px">\r\n    <td colspan="3"></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n\r\n<table width="100%" style="margin-top: 30px;" cellpadding="0" cellspacing="0">\r\n	<tr>\r\n		<td style="height: 45px; background-color: #444544; display: block !important;"></td>\r\n	</tr>\r\n</table>\r\n</td>\r\n</tr>\r\n</table>', 1, ''),
	(27, 'catalog coupon reminder', 'catalog coupon reminder', 'catalog_coupon_reminder', '0', '<!-- 		@page { margin: 0.79in } 		P { margin-bottom: 0.08in } 	-->\r\n<p style="background: #ffffff none repeat scroll 0% 0%; margin-left: 0.5in; margin-bottom: 0in; -moz-background-clip: -moz-initial; -moz-background-origin: -moz-initial; -moz-background-inline-policy: -moz-initial"><span style="font-family: Verdana,sans-serif;"><span style="font-size: x-small;"><span>Dear {name}. I just wish to inform you that we are currently running a campaign for all the clients who received our catalogue earlier. This means that in the next 4 days, you get </span></span></span><span style="color: #ff0000;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: x-small;"><span>{discount} </span></span></span></span><span style="font-family: Verdana,sans-serif;"><span style="font-size: x-small;"><span>off everything you buy, and since our products are already competitively priced, it is a really good offer. You can use the code: {coupon_code} when you order to get the discount, but remember you have 4 days from now to decide!</span></span></span></p>', 1, ''),
	(30, 'First Mail After Order Purchased', 'Mail After Order Purchased', 'first_mail_after_order_purchased', '0', '<p>Hi {name}, <br />You made an order with us 7 days ago and to show our appreciation of you as a customer we send you discount code to use the next time you visit our store</p>\r\n<p>{url}</p>\r\n<p>discount amount : {coupon_amount}</p>\r\n<p>discount coupon code : {coupon_code}</p>\r\n<p>valid upto : {coupon_duration}</p>\r\n<p>Thank you.</p>', 1, ''),
	(32, 'Second Mail After Order Purchased', 'Second Mail After Order Purchased', 'second_mail_after_order_purchased', '0', '<p>Hi {name}, <br />You made an order with us 10 days ago and to show our appreciation of you as a customer we send you discount code to use the next time you visit our store</p>\r\n<p>{url}</p>\r\n<p>discount amount : {coupon_amount}</p>\r\n<p>discount coupon code : {coupon_code}</p>\r\n<p>valid upto : {coupon_duration}</p>\r\n<p>Thank you.</p>', 1, ''),
	(33, 'Third Mail After Order Purchased', 'Third Mail After Order Purchased', 'third_mail_after_order_purchased', '0', '<p>Hi {name}, <br />You made an order with us 21 days ago and to show our appreciation of you as a customer we send you discount code to use the next time you visit our store</p>\r\n<p>{url}</p>\r\n<p>discount amount : {coupon_amount}</p>\r\n<p>discount coupon code : {coupon_code}</p>\r\n<p>valid upto : {coupon_duration}</p>\r\n<p>Thank you.</p>', 1, ''),
	(34, 'Catalog Send Mail', 'Catalog Request', 'catalog', '0', '<p>Dear, <strong>{name}</strong></p>\r\n<p>We get your request for catalog. Here, you can found attached catalogs.</p>\r\n<p> </p>\r\n<p>Thank you.</p>', 1, ''),
	(50, 'Economic Invoice', 'Invoice', 'economic_inoice', '0', '<table style="border: 1px solid #ccc; background: #fff; width: 600px;" cellpadding="0" cellspacing="0">\r\n<tbody>\r\n<tr>\r\n<td>\r\n<table style="width: 100%; background: #f7f7f7;" border="0" cellpadding="0" cellspacing="0">\r\n<tbody>\r\n<tr>\r\n<td style="width: 20px;"></td>\r\n<td style="line-height: 25px;">\r\n<table style="width: 100%; padding-top: 10px;" cellpadding="0" cellspacing="0">\r\n<tbody>\r\n<tr>\r\n<td style="height: 94px;" width="400px"><a href="http://redcomponent.com" target="_blank"> <img src="http://redcomponent.com/images/redcomponent_logo.png" style="width: 340px; height: auto;" /> </a></td>\r\n<td style="font-size: 12px; color: #666666; float: right; text-align: right; font-family: verdana; vertical-align: top;">{order_date}</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n<td style="width: 20px;"></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<table style="width: 100%;" cellpadding="0" cellspacing="0">\r\n<tbody>\r\n<tr>\r\n<td style="height: 20px; background-color: #444544;"></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<table border="0" cellpadding="0" cellspacing="0">\r\n<tbody>\r\n<tr>\r\n<td colspan="3" style="height: 20px;"></td>\r\n</tr>\r\n<tr>\r\n<td style="width: 20px;"></td>\r\n<td style="padding-bottom: 30px;">\r\n<p style="font-size: 14px; font-family: verdana; color: #666666; text-align: justify;"><strong>Hi {name}</strong><br /><br />Attached is your invoice.<br /><br />Regards,<br />redCOMPONENT</p>\r\n</td>\r\n<td style="width: 20px;"></td>\r\n</tr>\r\n<tr style="height: 160px;">\r\n<td colspan="3"></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<table style="width: 100%;" cellpadding="0" cellspacing="0">\r\n<tbody>\r\n<tr>\r\n<td style="height: 45px; background-color: #444544; display: block !important;"></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>', 1, ''),
	(54, 'My wishlist mail', 'My wishlist', 'mywishlist_mail', '0', 'hi,{name}<!--{product_loop_start}--><table style="width: 100%;" border="0" cellpadding="5" cellspacing="0"><tbody><tr valign="top"><td width="40%"><div style="float: left; width: 195px; height: 230px; text-align: center;">{product_thumb_image}<div>{product_name}</div><div>{product_price}</div></div></td></tr></tbody></table><!--{product_loop_end}-->Regards,{from_name}', 1, ''),
	(64, 'Order Special Discount Mail', 'Admin applied discount (special offer)', 'order_special_discount', '0', 'You got {special_discount} that is {special_discount_amount}.<table style="width: 100%;" border="0" cellpadding="5" cellspacing="0"><tbody><tr><td><br /></td><td><table style="width: 100%;" align="right" border="0" cellpadding="2" cellspacing="0"><tbody><tr><td align="right">ABC Company -- abc.com</td></tr><tr><td align="right">abccompany.com</td></tr><tr><td align="right">Street Address</td></tr><tr><td align="right">Address line 2</td></tr><tr><td align="right">County</td></tr><tr><td align="right">Country</td></tr><tr><td></td></tr><tr><td align="right">Telephone Number : 11325-3251</td></tr><tr><td></td></tr><tr><td align="right">E-mail : abccompany@abc.om</td></tr></tbody></table></td></tr><tr><td style="font-weight: bold" colspan="2">Some Title</td></tr><tr><td colspan="2">Some Intro text...Lorem Ipsum is simply dummy 			text of the printing and typesetting industry. Lorem Ipsum has been 			the industrys standard dummy text ever since the 1500s, when an 			unknown printer took a galley of type and scrambled it to make a type 			specimen book. It has survived not only five centuries...</td></tr><tr><td colspan="2"><table style="width: 100%;" border="0" cellpadding="2" cellspacing="0"><tbody><tr style="background-color: #cccccc"><th align="left">Order Information</th></tr><tr></tr><tr><td>Order id : {order_id}</td></tr><tr><td>Order Number : {order_number}</td></tr><tr><td>Order Date : {order_date}</td></tr><tr><td>Order Status : {order_status}</td></tr></tbody></table></td></tr><tr><td colspan="2"><table style="width: 100%;" border="0" cellpadding="2" cellspacing="0"><tbody><tr style="background-color: #cccccc"><th align="left">Billing Address Information</th></tr><tr></tr><tr><td>{billing_address}</td></tr></tbody></table></td></tr><tr><td colspan="2"><table style="width: 100%;" border="0" cellpadding="2" cellspacing="0"><tbody><tr style="background-color: #cccccc"><th align="left">Shipping Address Information</th></tr><tr></tr><tr><td>{shipping_address}</td></tr></tbody></table></td></tr><tr><td colspan="2"><table style="width: 100%;" border="0" cellpadding="2" cellspacing="0"><tbody><tr style="background-color: #cccccc"><th align="left">Order Details</th></tr><tr></tr><tr><td><table style="width: 100%;" border="0" cellpadding="2" cellspacing="2"><tbody><tr><td>Product Name</td><td>Note</td><td>Price</td><td>Quantity</td><td align="right">Total Price</td></tr><!--{product_loop_start}--><tr><td>{product_name}        {product_sku}</td><td>{product_wrapper}</td><td>{product_price}</td><td>{product_quantity}</td><td align="right">{product_total_price}</td></tr><!--{product_loop_end}--></tbody></table></td></tr><tr><td></td></tr><tr><td><table style="width: 100%;" border="0" cellpadding="2" cellspacing="2"><tbody><tr align="left"><td align="left"><strong>Order Subtotal : </strong></td><td align="right">{product_subtotal}</td></tr><tr align="left"><td align="left"><strong>TAX : </strong></td><td align="right">{order_tax}</td></tr><tr align="left"><td align="left"><strong>Discount : </strong></td><td align="right">{order_discount}</td></tr><tr align="left"><td align="left"><strong>{special_discount_lbl} </strong></td><td align="right">{special_discount_amount}</td></tr><tr align="left"><td align="left"><strong>Shipping : </strong></td><td align="right">{order_shipping}</td></tr><tr align="left"><td colspan="2" align="left"><hr /></td></tr><tr align="left"><td align="left"><strong>Total :</strong></td><td align="right">{order_total}</td></tr><tr align="left"><td colspan="2" align="left"><hr /></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table>', 1, ''),
	(74, 'News letter ', 'News Letter confirmation', 'newsletter_confirmation', '0', '<p>hi {name},</p>\r\n<p>Confirm your News letter {link}.</p>', 1, ''),
	(84, 'NewsLetter cancellation ', 'NewsLetter cancellation ', 'newsletter_cancellation', '0', 'NewsLetter cancellationNewsLetter cancellation NewsLetter cancellation NewsLetter cancellationNewsLetter cancellation NewsLetter cancellation', 1, ''),
	(85, 'Invoice Mail', 'Invoice Mail', 'invoice_mail', '0', '<table style="border: 1px solid #ccc;background: #fff; width:600px;">\r\n<tr>\r\n<td>\r\n	<div style="padding: 10px 20px;">\r\n		<table width="100%">\r\n	<tr>\r\n		<td width="400px">\r\n			<a href="http://redcomponent.com" target="_blank"> <img src="http://redcomponent.com/images/redcomponent_logo.png" style="width: 340px; height: auto; padding-top: 20px;" /> </a>\r\n		</td>\r\n		<td style="font-size: 12px; color: #878787; float: right;">\r\n			{order_date}\r\n		</td>\r\n	</tr>\r\n</table>\r\n	</div>\r\n	<table width="100%">\r\n	<tr>\r\n		<td style="height: 20px; background-color: #444544;"></td>\r\n	</tr>\r\n</table>\r\n	<div style="padding: 10px 20px;">\r\n		<p style="font-size: 24px; font-face: verdana; color: #616161; text-align: justify;">Thank you for your order!</p>\r\n		<p style="font-size: 14px; font-face: verdana; color: #616161; text-align: justify;">Thank you for ordering from redCOMPONENT!<br />To download your purchased products please follow the link in the bottom of this mail.</p>\r\n		<p style="font-size: 14px; font-face: verdana; color: #616161; text-align: justify;"> </p>\r\n		<p style="font-size: 14px; font-face: verdana; color: #616161; text-align: justify;"><strong>Products ordered:</strong></p>\r\n		<table style="width: 100%;" border="0">\r\n		<tbody>\r\n		<!--{product_loop_start}-->\r\n		<tr style="border-bottom: 1px solid #F1F1F1;">\r\n		<td><span style="font-size: 14px; font-face: verdana; color: #616161; text-align: justify;"><strong>{product_name}{without_vat}</strong></span></td>\r\n		<td><span style="font-size: 14px; font-face: verdana; color: #616161; text-align: justify;">{product_price}</span></td>\r\n		<td><span style="font-size: 14px; font-face: verdana; color: #616161; text-align: justify;">{product_quantity}</span></td>\r\n		<td align="right"><span style="font-size: 14px; font-face: verdana; color: #616161; text-align: right;">{product_total_price}</span></td>\r\n		</tr>\r\n		<!--{product_loop_end}-->\r\n		<tr>\r\n		<td colspan="3"><span style="font-size: 14px; font-face: verdana; color: #616161; text-align: justify;"><strong>VAT</strong></span></td>\r\n		<td align="right"><span style="font-size: 14px; font-face: verdana; color: #616161; text-align: justify;">{sub_total_vat}</span></td>\r\n		</tr>\r\n		<tr>\r\n		<td colspan="3"><span style="font-size: 14px; font-face: verdana; color: #616161; text-align: justify;"><strong>Total</strong></span></td>\r\n		<td align="right"><span style="font-size: 14px; font-face: verdana; color: #616161; text-align: justify;">{order_total}</span></td>\r\n		</tr>\r\n		</tbody>\r\n		</table>\r\n		<p style="text-align: justify;"> </p>\r\n		<p style="font-size: 14px; font-face: verdana; color: #616161; text-align: justify;"><strong>Billing information: </strong></p>\r\n		<div style="font-size: 14px; font-face: verdana; color: #616161; text-align: justify;">{billing_address}</div>\r\n		<p> </p>\r\n		<p style="font-size: 14px; font-face: verdana; color: #616161; text-align: justify;"><strong>Additional information:</strong></p>\r\n		<p style="font-size: 14px; font-face: verdana; color: #616161; text-align: justify;">{customer_note}</p>\r\n		<p> </p>\r\n		<p style="font-size: 14px; font-face: verdana; color: #616161; text-align: justify;"><strong>Order details:</strong></p>\r\n		<p style="font-size: 14px; font-face: verdana; color: #616161; text-align: justify;">To see the details of your order and to download the products please click {order_detail_link}</p>\r\n		<p style="font-size: 14px; font-face: verdana; color: #616161; text-align: justify;"> </p>\r\n		<p style="font-size: 14px; font-face: verdana; color: #616161; text-align: justify;">Regards,<br />redCOMPONENT</p>\r\n	</div>\r\n<table width="100%" style="margin-top: 30px;">\r\n	<tr>\r\n		<td style="height: 45px; background-color: #444544; display: block !important;"></td>\r\n	</tr>\r\n</table>\r\n</td>\r\n</tr>\r\n</table>', 1, ''),
	(86, 'Product Subscription Mail', 'Mail for product Subscription ', 'subscription_renewal_mail', '0', '<h1>Product Subscription Renew</h1>\r\n<h3>Dear,</h3>\r\n<p><span>{firstname} {lastname}</span></p>\r\n<p>Your Subscription for <strong>{product_name}</strong> is going to expired on <span>{subsciption_enddate}</span></p>\r\n<h2>Your Subscription Detail is as below</h2>\r\n<table border="0">\r\n<tbody>\r\n<tr>\r\n<td>Subscribe Product :</td>\r\n<td>{product_name}</td>\r\n</tr>\r\n<tr>\r\n<td>Subscription Period :</td>\r\n<td>{subscription_period}</td>\r\n</tr>\r\n<tr>\r\n<td>Subscription Price : </td>\r\n<td>{subscription_price}</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p>Click here <em>{product_link}</em> and renew it</p>', 1, ''),
	(94, 'Giftcard Mail', 'Giftcard Mail', 'giftcard_mail', '0', '<table><tr><td ><span>{giftcard_price_lbl}</span></td><td>{giftcard_price}</td></tr><tr><td ><span>{giftcard_reciver_name_lbl}</span></td><td>{giftcard_reciver_name}</td></tr><tr><td>{giftcard_reciver_email_lbl}</td><td>{giftcard_reciver_email}</td></tr><tr><td>{giftcard_code_lbl}</td><td>{giftcard_code}</td></tr><tr><td></td><td>{giftcard_desc}</td></tr><tr><td></td><td>{giftcard_price}</td></tr><tr><td>{giftcard_validity_from}{giftcard_validity_to}</td></tr><tr><td>{giftcard_image}</td></tr><tr><td>{giftcard_validity}</td></tr></table>', 1, ''),
	(105, 'Quotation Mail', 'Quotation Mail for {quotation_id} - {quotation_status} - {quotation_total}', 'quotation_mail', '0', '<table border="0" cellspacing="0" cellpadding="5" width="100%">\r\n<tbody>\r\n<tr>\r\n<td>\r\n<table border="0" cellspacing="0" cellpadding="2" width="100%">\r\n<tbody>\r\n<tr style="background-color: #cccccc">\r\n<th align="left">{quotation_information_lbl}</th>\r\n</tr>\r\n<tr>\r\n<td>{quotation_id_lbl} : {quotation_id}</td>\r\n</tr>\r\n<tr>\r\n<td>{quotation_number_lbl} : {quotation_number}</td>\r\n</tr>\r\n<tr>\r\n<td>{quotation_date_lbl} : {quotation_date}</td>\r\n</tr>\r\n<tr>\r\n<td>{quotation_status_lbl} : {quotation_status}</td>\r\n</tr>\r\n<tr>\r\n<td>{quotation_note_lbl} : {quotation_note}</td>\r\n</tr>\r\n<tr>\r\n<td>{quotation_detail_link}</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n<tr>\r\n<td>\r\n<table border="0" cellspacing="0" cellpadding="2" width="100%">\r\n<tbody>\r\n<tr style="background-color: #cccccc">\r\n<th align="left">{billing_address_information_lbl}</th>\r\n</tr>\r\n<tr>\r\n<td>{billing_address}</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n<tr>\r\n<td>\r\n<table border="0" cellspacing="0" cellpadding="2" width="100%">\r\n<tbody>\r\n<tr style="background-color: #cccccc">\r\n<th align="left">{quotation_detail_lbl}</th>\r\n</tr>\r\n<tr>\r\n<td>\r\n<table border="0" cellspacing="2" cellpadding="2" width="100%">\r\n<tbody>\r\n<tr>\r\n<td>{product_name_lbl}</td>\r\n<td>{note_lbl}</td>\r\n<td>{price_lbl}</td>\r\n<td>{quantity_lbl}</td>\r\n<td align="right">{total_price_lbl}</td>\r\n</tr>\r\n<!--{product_loop_start}-->\r\n<tr>\r\n<td>{product_name}{product_s_desc}({product_number})<br />{product_userfields}<br />{product_attribute}<br />{product_accessory}</td>\r\n<td>{product_wrapper}<br />{product_thumb_image}</td>\r\n<td>{product_price}</td>\r\n<td>{product_quantity}</td>\r\n<td align="right">{product_total_price}</td>\r\n</tr>\r\n<!--{product_loop_end}-->\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n<tr>\r\n<td></td>\r\n</tr>\r\n<tr>\r\n<td>\r\n<table border="0" cellspacing="2" cellpadding="2" width="100%">\r\n<tbody>\r\n<tr align="left">\r\n<td align="left"><strong>{quotation_subtotal_lbl} : </strong></td>\r\n<td align="right">{quotation_subtotal}</td>\r\n</tr>\r\n<tr align="left">\r\n<td colspan="2" align="left">\r\n<hr />\r\n</td>\r\n</tr>\r\n<tr align="left">\r\n<td align="left"><strong>{total_lbl} :</strong></td>\r\n<td align="right">{quotation_total}</td>\r\n</tr>\r\n<tr align="left">\r\n<td colspan="2" align="left">\r\n<hr />\r\n<br /> \r\n<hr />\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>', 1, ''),
	(150, 'Catalogue Order Mail', 'Catalogue Order Mail:', 'catalogue_order', '0', '<table style="width: 100%;" border="0" cellpadding="5" cellspacing="0"><tbody><tr><td><br /></td><td><table style="width: 100%;" align="right" border="0" cellpadding="2" cellspacing="0"><tbody><tr><td align="right">ABC Company -- abc.com</td></tr><tr><td align="right">abccompany.com</td></tr><tr><td align="right">Street Address</td></tr><tr><td align="right">Address line 2</td></tr><tr><td align="right">County</td></tr><tr><td align="right">Country</td></tr><tr><td></td></tr><tr><td align="right">Telephone Number : 11325-3251</td></tr><tr><td></td></tr><tr><td align="right">E-mail : abccompany@abc.om</td></tr></tbody></table></td></tr><tr><td style="font-weight: bold" colspan="2">Some Title</td></tr><tr><td colspan="2">Some Intro text...Lorem Ipsum is simply dummy    text of the printing and typesetting industry. Lorem Ipsum has been    the industry''s standard dummy text ever since the 1500s, when an    unknown printer took a galley of type and scrambled it to make a type    specimen book. It has survived not only five centuries...</td></tr><tr><td colspan="2"><table style="width: 100%;" border="0" cellpadding="2" cellspacing="0"><tbody><tr style="background-color: #cccccc"><th align="left">{order_information_lbl}</th></tr><tr></tr><tr><td>{order_id_lbl} : {order_id}</td></tr><tr><td>{order_number_lbl} : {order_number}</td></tr><tr><td>{order_date_lbl} : {order_date}</td></tr><tr><td>{order_status_lbl} : {order_status}</td></tr></tbody></table></td></tr><tr><td colspan="2"><table style="width: 100%;" border="0" cellpadding="2" cellspacing="0"><tbody><tr style="background-color: #cccccc"><th align="left">{billing_address_information_lbl}</th></tr><tr></tr><tr><td>{billing_address}</td></tr></tbody></table></td></tr><tr><td colspan="2"><table style="width: 100%;" border="0" cellpadding="2" cellspacing="0"><tbody><tr style="background-color: #cccccc"><th align="left">{shipping_address_information_lbl}</th></tr><tr></tr><tr><td>{shipping_address}</td></tr></tbody></table></td></tr><tr><td colspan="2"><table style="width: 100%;" border="0" cellpadding="2" cellspacing="0"><tbody><tr style="background-color: #cccccc"><th align="left">{order_detail_lbl}</th></tr><tr></tr><tr><td><table style="width: 100%;" border="0" cellpadding="2" cellspacing="2"><tbody><tr><td>{product_name_lbl}</td><td>{note_lbl}</td><td>{quantity_lbl}</td></tr><!--{product_loop_start}--><tr><td>{pro_name}<br /> {product_userfields}</td><td>{pro_note}</td><td>{pro_quantity}</td></tr><!--{product_loop_end}--></tbody></table></td></tr></tbody></table></td></tr><tr><td colspan="2"><table style="width: 100%;" border="0" cellpadding="2" cellspacing="0"><tbody><tr style="background-color: #cccccc"><th align="left">Payment Status</th></tr><tr></tr><tr><td>{order_payment_status}{shipping_method_lbl}{shipping_method}</td></tr></tbody></table></td></tr><tr><td colspan="2"><table style="width: 100%;" border="0" cellpadding="2" cellspacing="0"><tbody><tr style="background-color: #cccccc"><th align="left">Order url</th></tr><tr></tr><tr><td>{order_detail_link}</td></tr></tbody></table></td></tr></tbody></table>', 1, ''),
	(160, 'Quotation User Register Mail', 'Quotation User Register Mail:', 'quotation_user_register', '0', '<table><tr><td>Username</td><td> : </td><td>{username}</td></tr><tr><td>Password</td><td> : </td><td>{password}</td></tr><tr><td>Click here</td><td> : </td><td>{link}</td></tr></table>', 1, ''),
	(175, 'RequestTaxExemptMail', 'RequestTaxExemptMail:', 'request_tax_exempt_mail', '0', '<table style="width: 100%;" border="0" cellpadding="5" cellspacing="0"><tbody><tr><td>Vat Number</td><td>{vat_number}</td></tr><tr><td>User Name</td><td>{username}</td></tr><tr><td>Company Name</td><td>{company_name}</td></tr><tr><td>Country</td><td>{country}</td></tr><tr><td>State</td><td>{state}</td></tr><tr><td>Phone</td><td>{phone}</td></tr><tr><td>Zipcode</td><td>{zipcode}</td></tr><tr><td>Address</td><td>{address}</td></tr><tr><td>City</td><td>{city}</td></tr></tbody></table>', 1, '');

INSERT IGNORE INTO `#__redshop_mail` (`mail_id`, `mail_name`, `mail_subject`, `mail_section`, `mail_order_status`, `mail_body`, `published`, `mail_bcc`) VALUES
	(185, 'Downloadable Email', 'Link to download your newly purchased product(s)', 'downloadable_product_mail', '0', '<table style="border: 1px solid #ccc; background: #fff; width: 600px;" cellpadding="0" cellspacing="0">\r\n<tbody>\r\n<tr>\r\n<td style="line-height: 25px;">\r\n<table style="width: 100%; background: #f7f7f7;" border="0" cellpadding="0" cellspacing="0">\r\n<tbody>\r\n<tr>\r\n<td colspan="3" style="height: 10px;"></td>\r\n</tr>\r\n<tr>\r\n<td style="width: 20px;"></td>\r\n<td>\r\n<table style="width: 100%;" cellpadding="0" cellspacing="0">\r\n<tbody>\r\n<tr>\r\n<td width="400px"><a href="http://redcomponent.com" target="_blank"> <img src="http://redcomponent.com/images/redcomponent_logo.png" style="width: 340px; height: auto; padding-top: 20px;" /> </a></td>\r\n<td style="font-size: 12px; color: #878787; float: right; font-family: verdana; vertical-align: top;">{order_date}</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n<td style="width: 20px;"></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<table style="width: 100%;" cellpadding="0" cellspacing="0">\r\n<tbody>\r\n<tr>\r\n<td style="height: 20px; background-color: #444544;"></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<table border="0" cellpadding="0" cellspacing="0">\r\n<tbody>\r\n<tr>\r\n<td colspan="3" style="height: 20px;"></td>\r\n</tr>\r\n<tr>\r\n<td style="width: 20px;"></td>\r\n<td style="line-height: 25px;">\r\n<p style="font-size: 14px; font-family: verdana; color: #616161; text-align: justify;"><strong>Dear {fullname}</strong></p>\r\n<p style="font-size: 14px; font-family: verdana; color: #616161; text-align: justify;">Thanks for your recent purchase at our store. Here are the link(s) where you can download file/product that you have purchased.</p>\r\n<p style="font-size: 14px; font-family: verdana; color: #616161; text-align: justify;">Order Date : {order_date}<br />Order # : {order_number}<br />Download Links :</p>\r\n<p style="font-size: 14px; font-family: verdana; color: #616161; text-align: justify;">{product_serial_loop_start} {product_name} - {token} <br /> {product_serial_loop_end}</p>\r\n<p style="font-size: 14px; font-family: verdana; color: #616161; text-align: justify;">Once again, thank you for shopping!</p>\r\n</td>\r\n<td style="width: 20px;"></td>\r\n</tr>\r\n<tr style="height: 160px;">\r\n<td colspan="3"></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<table style="margin-top: 30px; width: 100%;" cellpadding="0" cellspacing="0">\r\n<tbody>\r\n<tr>\r\n<td style="height: 45px; background-color: #444544;"></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>', 1, ''),
	(186, 'Review', 'Review About Product', 'review_mail', '0', '<p>To Admin,</p><p>Username: {username}</p><p>Product : {product_name}</p><p>Please check this link : {product_link}</p><p>Title : {title}</p><p>Comment : {comment}</p>', 1, ''),
	(187, 'Notify Stock', 'Stock Update Notification for {product_name}', 'notify_stock_mail', '0', '<table border="0" cellspacing="0" cellpadding="5" width="100%"><tbody><tr><td><table border="0" cellspacing="0" cellpadding="2" width="100%"><tbody><tr style="background-color: #cccccc"><th align="left">{stocknotify_intro_text}</th></tr><tr><td>{product_detail}</td></tr></tbody></table></td></tr></tbody></table>', 1, ''),
	(188, 'Invoice Mail', 'Invoice Mail', 'invoicefile_mail', '0', '<table><tr><td><div style="padding: 10px 20px;"><table width="100%" border="0" cellspacing="0" cellspacing="0"><tr><td width="500px"><span style="font-size: 45px;"><strong><span style="color: #cc3333;">red</span>COMPONENT</strong></span></td><td width="125px" align="right" style="font-size: 12px; color: #878787;"><p style="text-align: right;">{order_number_lbl} {order_number}</p><p style="text-align: right;">Invoice No: {invoice_number}</p><p style="text-align: right;">Date:{order_date}</p></td></tr></table></div><table width="100%"><tr><td style="height: 20px; background-color: #444544;"></td></tr></table><div style="padding: 10px 20px;"><p style="font-size: 24px; font-face: verdana; color: #616161; text-align: justify;">Thank you for your order!</p><p style="font-size: 14px; font-face: verdana; color: #616161; text-align: justify;">Thank you for ordering from redCOMPONENT!<br />To download your purchased products please follow the link in the bottom of this mail.</p><p style="font-size: 14px; font-face: verdana; color: #616161; text-align: justify;"> </p><p style="font-size: 14px; font-face: verdana; color: #616161; text-align: justify;"><strong>Products ordered:</strong></p><table style="width: 100%;" border="0" cellpadding="0" cellspacing="0"><tbody><!--{product_loop_start}--><tr style="border-bottom: 1px solid #F1F1F1;"><td><span style="font-size: 14px; font-face: verdana; color: #616161; text-align: justify;"><strong>{product_name}{without_vat}</strong></span></td><td><span style="font-size: 14px; font-face: verdana; color: #616161; text-align: justify;">{product_price}</span></td><td><span style="font-size: 14px; font-face: verdana; color: #616161; text-align: justify;">{product_quantity}</span></td><td><span style="font-size: 14px; font-face: verdana; color: #616161;">{product_total_price}</span></td></tr><!--{product_loop_end}--><tr><td colspan="2">&nbsp;</td><td><span style="font-size: 14px; font-face: verdana; color: #616161;"><strong>VAT</strong></span></td><td><span style="font-size: 14px; font-face: verdana; color: #616161;">{sub_total_vat}</span></td></tr><tr><td colspan="2">&nbsp;</td><td><span style="font-size: 14px; font-face: verdana; color: #616161;"><strong>Total</strong></span></td><td><span style="font-size: 14px; font-face: verdana; color: #616161;">{order_total}</span></td></tr></tbody></table><div style="font-size: 14px; font-face: verdana; color: #616161; text-align: justify;"><p><strong>Billing information: </strong></p>{billing_address}</div><p style="font-size: 14px; font-face: verdana; color: #616161; text-align: justify;">To see the details of your order and to download the products please click {order_detail_link}</p><p style="font-size: 14px; font-face: verdana; color: #616161; text-align: justify;">Regards,<br />redCOMPONENT</p></div><table width="100%" style="margin-top: 30px;"><tr><td style="height: 45px; background-color: #444544; display: block !important;"></td></tr></table></td></tr></table>', 1, '');

INSERT IGNORE INTO `#__redshop_shopper_group` ( `shopper_group_id` ,`shopper_group_name` ,`shopper_group_customer_type` ,`shopper_group_portal` ,`shopper_group_categories` ,`shopper_group_url` ,`shopper_group_logo` ,`shopper_group_introtext` ,`shopper_group_desc` ,`parent_id` ,`published`)
VALUES (1 , 'Default Private', '1', '0', '', '', '', 'This is the default private shopper group.', 'This is the default private shopper group.', '0', '1');

INSERT IGNORE INTO `#__redshop_shopper_group` ( `shopper_group_id` ,`shopper_group_name` ,`shopper_group_customer_type` ,`shopper_group_portal` ,`shopper_group_categories` ,`shopper_group_url` ,`shopper_group_logo` ,`shopper_group_introtext` ,`shopper_group_desc` ,`parent_id` ,`published`)
VALUES (2 , 'Default Company', '0', '0', '', '', '', 'This is the default Company shopper group.', 'This is the default Company shopper group.', '0', '1');

INSERT IGNORE INTO `#__redshop_shopper_group` ( `shopper_group_id` ,`shopper_group_name` ,`shopper_group_customer_type` ,`shopper_group_portal` ,`shopper_group_categories` ,`shopper_group_url` ,`shopper_group_logo` ,`shopper_group_introtext` ,`shopper_group_desc` ,`parent_id`, `published`)
VALUES (3 , 'Default Tax Exempt', '0', '0', '', '', '', 'This is the Default Tax Exempt shopper group.', 'This is the Default Tax Exempt shopper group.', '0', '1');

INSERT IGNORE INTO `#__redshop_tax_group` (`id` ,`name` ,`published`)
VALUES (1, 'Default','1');

INSERT IGNORE INTO `#__redshop_economic_accountgroup` (`accountgroup_id`, `accountgroup_name`, `economic_vat_account`, `economic_nonvat_account`, `economic_discount_nonvat_account`, `economic_shipping_vat_account`, `economic_shipping_nonvat_account`, `economic_discount_product_number`, `published`, `economic_service_nonvat_account`, `economic_discount_vat_account`) VALUES
	(1, 'default account group', '4001', '4000', '4000', '4001', '4000', '191919', 1, '', '4001');

INSERT IGNORE INTO `#__redshop_newsletter` (`newsletter_id` , `name` , `subject` , `body` , `template_id` , `published`)
VALUES ('1', 'News Letter Demo', 'News Letter Demo', 'User Name : {username} Email : {email}', '29', '1');

INSERT IGNORE INTO `#__redshop_shipping_rate` (`shipping_rate_id`, `shipping_rate_name`, `shipping_class`, `shipping_rate_country`, `shipping_rate_zip_start`, `shipping_rate_zip_end`, `shipping_rate_weight_start`, `company_only`, `apply_vat`, `shipping_rate_weight_end`, `shipping_rate_volume_start`, `shipping_rate_volume_end`, `shipping_rate_ordertotal_start`, `shipping_rate_ordertotal_end`, `shipping_rate_priority`, `shipping_rate_value`, `shipping_rate_package_fee`, `shipping_location_info`, `shipping_rate_length_start`, `shipping_rate_length_end`, `shipping_rate_width_start`, `shipping_rate_width_end`, `shipping_rate_height_start`, `shipping_rate_height_end`, `shipping_rate_on_product`, `shipping_rate_on_category`, `shipping_tax_group_id`, `shipping_rate_state`) VALUES
	(1, 'Demo Rate', 'default_shipping', '', '', '', 0.00, 0, 0, 0.00, 0.00, 0.00, 0.000, 0.000, 0, 0.00, 0.00, '', 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, '', '', 0, '');

INSERT IGNORE INTO `#__redshop_shipping_boxes` (`shipping_box_id`, `shipping_box_name`, `shipping_box_length`, `shipping_box_width`, `shipping_box_height`, `shipping_box_priority`, `published`) VALUES
	(1, 'Box1', 1.00, 1.00, 1.00, 1, 1);

LOCK TABLES `#__redshop_category` WRITE;
ALTER TABLE `#__redshop_category` DISABLE KEYS;
INSERT INTO `#__redshop_category` VALUES (NULL, 'ROOT', '', '', 0, '', 0, '', '', '', '', '', '', '', '', '', 1, '0000-00-00 00:00:00', 0, '', '', 0, 'append', 'root', '', 0, 0, 0, 0, 1, '', '0000-00-00 00:00:00', '0000-00-00 00:00:00', '', '', '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
ALTER TABLE `#__redshop_category` ENABLE KEYS;
UNLOCK TABLES;
