<?php define ('USPS_USERNAME', '162LORET7625');
define ('USPS_PASSWORD', '761CR76QH927');
define ('USPS_SERVER', 'production.shippingAPIs.com');
define ('USPS_PATH', '/shippingAPI.dll');
define ('USPS_PROXYSERVER', '');
define ('USPS_TAX_CLASS', '');
define ('USPS_HANDLINGFEE', '.00');
define ('USPS_PADDING', '10%');
define ('OVERRIDE_SOURCE_ZIP', '07006');
define ('USPS_INTLHANDLINGFEE', '5.00');
define ('USPS_MACHINABLE', '0');
define ('USPS_SHOW_DELIVERY_QUOTE', '0');
define ('USPS_REPORTERRORS', '0');
define ('USPS_STANDARDSHIPPING', '1');
define ('USPS_PREFIX', 'USPS');
define ('USPS_DOMESTIC_SHIPPING_METHOD', '');
define ('USPS_INTL0', '1');
define ('USPS_INTL1', '1');
define ('USPS_INTL2', '1');
define ('USPS_INTL3', '1');
define ('USPS_INTL4', '1');
define ('USPS_INTL5', '0');
define ('USPS_INTL6', '1');
define ('USPS_INTL7', '0');
define ('USPS_INTL8', '0');
define ('USPS_INTL9', '0');
define ('USPS_INTL10', '0');
define ('USPS_INTL11', '0');
define ('USPS_INTL0_TEXT', 'Global Express Guaranteed (GXG)');
define ('USPS_INTL1_TEXT', 'Global Express Guaranteed Non-Document Rectangular');
define ('USPS_INTL2_TEXT', 'Global Express Guaranteed Non-Document Non-Rectangular');
define ('USPS_INTL3_TEXT', 'USPS GXG Envelopes');
define ('USPS_INTL4_TEXT', 'Express Mail International');
define ('USPS_INTL5_TEXT', 'Express Mail International Flat Rate Envelope');
define ('USPS_INTL6_TEXT', 'Priority Mail International');
define ('USPS_INTL7_TEXT', 'Priority Mail International Flat Rate Envelope');
define ('USPS_INTL8_TEXT', 'Priority Mail International Medium Flat Rate Box');
define ('USPS_INTL9_TEXT', 'Priority Mail International Large Flat Rate Box');
define ('USPS_INTL10_TEXT', 'First-Class Mail International Large Envelope');
define ('USPS_INTL11_TEXT', 'First-Class Mail International Package');
define ('USPS_INTL12_TEXT', 'Priority Mail International Small Flat Rate Box');
?>