<?php
defined('_JEXEC') or die;
define('USPS_USERNAME', '');
define('USPS_PASSWORD', '');
define('USPS_SERVER', 'production.shippingapis.com');
define('USPS_PATH', '/ShippingAPI.dll');
define('USPS_PROXYSERVER', '');
define('USPS_TAX_CLASS', '');
define('USPS_HANDLINGFEE', '2.00');
define('USPS_PADDING', '10%');
define('OVERRIDE_SOURCE_ZIP', '07006');
define('USPS_INTLHANDLINGFEE', '5.00');
define('USPS_MACHINABLE', '0');
define('USPS_SHOW_DELIVERY_QUOTE', '0');
define('USPS_REPORTERRORS', '0');
define('USPS_STANDARDSHIPPING', '1');
define('USPS_PREFIX', 'USPS');
define('USPS_DOMESTIC_SHIPPING_METHOD', '');
define('USPS_SHIP0', '1');
define('USPS_SHIP1', '1');
define('USPS_SHIP2', '1');
define('USPS_SHIP3', '1');
define('USPS_SHIP4', '1');
define('USPS_SHIP5', '1');
define('USPS_SHIP6', '1');
define('USPS_SHIP7', '1');
define('USPS_SHIP8', '1');
define('USPS_SHIP9', '1');
define('USPS_SHIP10', '1');
define('USPS_SHIP11', '1');
define('USPS_SHIP12', '1');
define('USPS_SHIP13', '1');
define('USPS_SHIP14', '1');
define('USPS_SHIP15', '1');
define('USPS_SHIP16', '1');
define('USPS_SHIP17', '1');
define('USPS_SHIP18', '1');
define('USPS_SHIP19', '1');
define('USPS_SHIP20', '1');
define('USPS_SHIP21', '1');
define('USPS_SHIP22', '1');
define('USPS_SHIP23', '1');
define('USPS_SHIP24', '1');
define('USPS_SHIP25', '1');
define('USPS_SHIP26', '1');
define('USPS_SHIP27', '1');
define('USPS_SHIP28', '1');
define('USPS_SHIP29', '1');
define('USPS_SHIP0_COMMIT', 'Overnight, most locations');
define('USPS_SHIP1_COMMIT', 'Overnight, most locations');
define('USPS_SHIP2_COMMIT', 'Overnight, most locations');
define('USPS_SHIP3_COMMIT', 'Overnight, most locations');
define('USPS_SHIP4_COMMIT', 'Overnight, most locations');
define('USPS_SHIP5_COMMIT', 'Overnight, most locations');
define('USPS_SHIP6_COMMIT', 'Overnight, most locations');
define('USPS_SHIP7_COMMIT', 'Overnight, most locations');
define('USPS_SHIP8_COMMIT', 'Overnight, most locations');
define('USPS_SHIP9_COMMIT', 'Overnight, most locations');
define('USPS_SHIP10_COMMIT', 'Overnight, most locations');
define('USPS_SHIP11_COMMIT', 'Overnight, most locations');
define('USPS_SHIP12_COMMIT', 'Delivery within 2 days in most cases');
define('USPS_SHIP13_COMMIT', 'Delivery within 2 days in most cases');
define('USPS_SHIP14_COMMIT', 'Delivery within 2 days in most cases');
define('USPS_SHIP15_COMMIT', 'Delivery within 2 days in most cases');
define('USPS_SHIP16_COMMIT', 'Delivery within 2 days in most cases');
define('USPS_SHIP17_COMMIT', 'Delivery within 2 days in most cases');
define('USPS_SHIP18_COMMIT', 'Delivery within 2 days in most cases');
define('USPS_SHIP19_COMMIT', 'Delivery within 2 days in most cases');
define('USPS_SHIP20_COMMIT', 'Delivery within 2 days in most cases');
define('USPS_SHIP21_COMMIT', 'Delivery within 2 days in most cases');
define('USPS_SHIP22_COMMIT', 'Delivery within 2 days in most cases');
define('USPS_SHIP23_COMMIT', 'Delivery within 2 days in most cases');
define('USPS_SHIP24_COMMIT', 'Delivery within 2 days in most cases');
define('USPS_SHIP25_COMMIT', 'Delivery within 2 days in most cases');
define('USPS_SHIP26_COMMIT', 'Delivery within 2 days in most cases');
define('USPS_SHIP27_COMMIT', 'Delivery in 2 to 8 days');
define('USPS_SHIP28_COMMIT', 'Delivery in 2 to 8 days');
define('USPS_SHIP29_COMMIT', 'Delivery in 2 to 8 days');
define('USPS_INTL0', '1');
define('USPS_INTL1', '1');
define('USPS_INTL2', '1');
define('USPS_INTL3', '1');
define('USPS_INTL4', '1');
define('USPS_INTL5', '1');
define('USPS_INTL6', '1');
define('USPS_INTL7', '1');
define('USPS_INTL8', '1');
define('USPS_INTL9', '1');
define('USPS_INTL10', '1');
define('USPS_INTL11', '1');
define('USPS_INTL12', '1');
define('USPS_INTL13', '1');
define('USPS_INTL14', '1');
define('USPS_INTL15', '1');
define('USPS_INTL16', '1');
define('USPS_INTL17', '1');
define('USPS_INTL18', '1');
define('USPS_INTL19', '1');
define('USPS_INTL20', '1');
define('USPS_INTL21', '1');
define('USPS_SHIP0_TEXT', 'Priority Mail Express Hold For Pickup');
define('USPS_SHIP1_TEXT', 'Priority Mail Express');
define('USPS_SHIP2_TEXT', 'Priority Mail Express Sunday/Holiday Delivery');
define('USPS_SHIP3_TEXT', 'Priority Mail Express Flat Rate Boxes');
define('USPS_SHIP4_TEXT', 'Priority Mail Express Flat Rate Boxes Hold For Pickup');
define('USPS_SHIP5_TEXT', 'Priority Mail Express Sunday/Holiday Delivery Flat Rate Boxes');
define('USPS_SHIP6_TEXT', 'Priority Mail Express Flat Rate Envelope');
define('USPS_SHIP7_TEXT', 'Priority Mail Express Flat Rate Envelope Hold For Pickup');
define('USPS_SHIP8_TEXT', 'Priority Mail Express Sunday/Holiday Delivery Flat Rate Envelope');
define('USPS_SHIP9_TEXT', 'Priority Mail Express Legal Flat Rate Envelope');
define('USPS_SHIP10_TEXT', 'Priority Mail Express Legal Flat Rate Envelope Hold For Pickup');
define('USPS_SHIP11_TEXT', 'Priority Mail Express Sunday/Holiday Delivery Legal Flat Rate Envelope');
define('USPS_SHIP12_TEXT', 'Priority Mail');
define('USPS_SHIP13_TEXT', 'Priority Mail Large Flat Rate Box');
define('USPS_SHIP14_TEXT', 'Priority Mail Medium Flat Rate Box');
define('USPS_SHIP15_TEXT', 'Priority Mail Small Flat Rate Box');
define('USPS_SHIP16_TEXT', 'Priority Mail Flat Rate Envelope');
define('USPS_SHIP17_TEXT', 'Priority Mail Legal Flat Rate Envelope');
define('USPS_SHIP18_TEXT', 'Priority Mail Padded Flat Rate Envelope');
define('USPS_SHIP19_TEXT', 'Priority Mail Gift Card Flat Rate Envelope');
define('USPS_SHIP20_TEXT', 'Priority Mail Small Flat Rate Envelope');
define('USPS_SHIP21_TEXT', 'Priority Mail Window Flat Rate Envelope');
define('USPS_SHIP22_TEXT', 'First-Class Mail Parcel');
define('USPS_SHIP23_TEXT', 'First-Class Mail Letter');
define('USPS_SHIP24_TEXT', 'First-Class Mail Postcards');
define('USPS_SHIP25_TEXT', 'First-Class Mail Large Postcards');
define('USPS_SHIP26_TEXT', 'First-Class Mail Large Envelope');
define('USPS_SHIP27_TEXT', 'Standard Post');
define('USPS_SHIP28_TEXT', 'Media Mail');
define('USPS_SHIP29_TEXT', 'Library Mail');
define('USPS_INTL0_TEXT', 'Global Express Guaranteed (GXG)**');
define('USPS_INTL1_TEXT', 'Global Express Guaranteed Non-Document Rectangular');
define('USPS_INTL2_TEXT', 'Global Express Guaranteed Non-Document Non-Rectangular');
define('USPS_INTL3_TEXT', 'USPS GXG Envelopes**');
define('USPS_INTL4_TEXT', 'Priority Mail Express International');
define('USPS_INTL5_TEXT', 'Priority Mail Express International Flat Rate Boxes');
define('USPS_INTL6_TEXT', 'Priority Mail Express International Flat Rate Envelope');
define('USPS_INTL7_TEXT', 'Priority Mail Express International Legal Flat Rate Envelope');
define('USPS_INTL8_TEXT', 'Priority Mail International');
define('USPS_INTL9_TEXT', 'Priority Mail International Large Flat Rate Box');
define('USPS_INTL10_TEXT', 'Priority Mail International Medium Flat Rate Box');
define('USPS_INTL11_TEXT', 'Priority Mail International Small Flat Rate Box**');
define('USPS_INTL12_TEXT', 'Priority Mail International DVD Flat Rate priced box**');
define('USPS_INTL13_TEXT', 'Priority Mail International Large Video Flat Rate priced box**');
define('USPS_INTL14_TEXT', 'Priority Mail International Flat Rate Envelope**');
define('USPS_INTL15_TEXT', 'Priority Mail International Legal Flat Rate Envelope**');
define('USPS_INTL16_TEXT', 'Priority Mail International Padded Flat Rate Envelope**');
define('USPS_INTL17_TEXT', 'Priority Mail International Gift Card Flat Rate Envelope**');
define('USPS_INTL18_TEXT', 'Priority Mail International Small Flat Rate Envelope**');
define('USPS_INTL19_TEXT', 'Priority Mail International Window Flat Rate Envelope**');
define('USPS_INTL20_TEXT', 'First-Class Package International Service**');
define('USPS_INTL21_TEXT', 'First-Class Mail International Large Envelope**');
