<?php
/**
 * @package     RedSHOP.Backend
 * @subpackage  Table
 *
 * @copyright   Copyright (C) 2008 - 2017 redCOMPONENT.com. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE
 */

defined('_JEXEC') or die;

/**
 * The zipcode table
 *
 * @package     RedSHOP.Backend
 * @subpackage  Table.Catalog
 * @since       2.1.3
 */
class RedshopTableShopperGroup extends RedshopTable
{
    /**
     * The table name without prefix.
     *
     * @var string
     */
    protected $_tableName = 'redshop_shopper_group';

    /**
     * @var string
     */
    public $logo;

    /***
     * @var string
     */
    public $manufactures;

    /**
     * @var string
     */
    public $categories;

    protected function doStore($updateNulls = false)
    {
        $this->storeImage();
        $data = JFactory::getApplication()->input->post->get('jform', array(), 'array');

        if ( ! empty($data['manufactures'])) {
            $this->manufactures = implode(',', $data['manufactures']);
        }

        if ( ! empty($data['categories'])) {
            $this->categories = implode(',', $data['categories']);
        }

        return parent::doStore($updateNulls); // TODO: Change the autogenerated stub
    }

    protected function storeImage()
    {
        $app             = JFactory::getApplication();
        $logo            = $app->input->files->get('logo');
        $post            = $app->input->post->getArray();
        $shopperGroupDir = REDSHOP_FRONT_IMAGES_RELPATH . 'shopperlogo/';

        if ( ! empty($logo['name']) || ! empty($post['logo_tmp'])) {
            $logoPath = $shopperGroupDir . $post['logo'];

            if (JFile::exists($logoPath)) {
                JFile::delete($logoPath);
            }
        }

        if ( ! empty($logo['name'])) {
            $logoName = RedshopHelperMedia::cleanFileName($logo['name']);

            // Image Upload
            $logoType = JFile::getExt($logo['name']);

            $src  = $logo['tmp_name'];
            $dest = $shopperGroupDir . $logoName;

            if ($logoType == 'jpg' || $logoType == 'jpeg' || $logoType == 'gif' || $logoType == 'png') {
                JFile::upload($src, $dest);
                $this->logo = $logoName;
            }
        } elseif ( ! empty($post['logo_tmp'])) {
            $imageSplit = explode('/', $post['logo_tmp']);
            $logoName   = RedshopHelperMedia::cleanFileName($imageSplit[count($imageSplit) - 1]);
            $this->logo = $logoName;

            // Image copy
            $src  = JPATH_ROOT . '/' . $post['logo_tmp'];
            $dest = $shopperGroupDir . $logoName;

            copy($src, $dest);
        }

        if (empty($post['jform']['id']) && Redshop::getConfig()->get('NEW_SHOPPER_GROUP_GET_VALUE_FROM')) {
            $destName     = time() . $post['logo'];
            $logoPath     = $shopperGroupDir . $post['logo'];
            $copyLogoPath = $shopperGroupDir . $destName;

            if (JFile::exists($logoPath)) {
                JFile::copy($logoPath, $copyLogoPath);
            }

            $this->logo = $destName;
        }
    }
}
